// ******************************************************************************
// * COPYRIGHT (c) 2007 by SVResearch, Harrisburg
// * All Rights Reserved
// ******************************************************************************
// * .Module Name     : SVMatroxStatusInformation
// * .File Name       : $Workfile:   SVMatroxStatusInformation.h  $
// * ----------------------------------------------------------------------------
// * .Current Version : $Revision:   1.0  $
// * .Check In Date   : $Date:   22 Apr 2013 15:27:22  $
// ******************************************************************************

#ifndef SV_MATROX_STATUS_INFORMATION_H
#define SV_MATROX_STATUS_INFORMATION_H

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SVMatroxLibrary/SVMatroxTypedefs.h"

#include <string>

/**
@SVObjectName Matrox Status Information

@SVObjectOverview This class will be used to hold the status information generated by Matrox for each function call.

@SVObjectOperations This class will present empty, clear, and data extraction operators.

*/
class SVMatroxStatusInformation  
{
public:
	typedef long SVFunctionCode;
	typedef std::string SVFunctionString;
	typedef SVMatroxStatusCode SVStatusCode;
	typedef SVMatroxStatusString SVStatusString;

	SVMatroxStatusInformation();
	SVMatroxStatusInformation( const SVMatroxStatusInformation& p_rObject );

	virtual ~SVMatroxStatusInformation();

	bool empty() const;

	void clear();

	const SVMatroxStatusInformation& operator=( const SVMatroxStatusInformation& p_rObject );

	SVStatusString GetCompleteString() const;

	SVStatusCode m_StatusCode;
	SVStatusString m_StatusString;

	SVFunctionCode m_FunctionCode;
	SVFunctionString m_FunctionString;

	long m_StatusSubCodeCount;

	SVStatusCode m_StatusSubCode[ 3 ];
	SVStatusString m_StatusSubString[ 3 ];

};

#endif // SV_MATROX_STATUS_INFORMATION_H

// ******************************************************************************
// * LOG HISTORY:
// ******************************************************************************
/*
$Log:   N:\PVCSarch65\ProjectFiles\archives\SVObserver_SRC\SVMatroxLibrary\SVMatroxStatusInformation.h_v  $
 * 
 *    Rev 1.0   22 Apr 2013 15:27:22   bWalter
 * Project:  SVObserver
 * Change Request (SCR) nbr:  814
 * SCR Title:  Upgrade SVObserver to Compile Using Visual Studio 2010
 * Checked in by:  bWalter;  Ben Walter
 * Change Description:  
 *   Initial check in to SVObserver_src.  (Merged with svo_src label SVO 6.10 Beta 008.)
 * 
 * /////////////////////////////////////////////////////////////////////////////////////
 * 
 *    Rev 1.1   23 Jul 2010 08:12:28   jspila
 * Project:  SVObserver
 * Change Request (SCR) nbr:  695
 * SCR Title:  Upgrade Acq to Allow for LUT, Light Reference, and Model Updates for GigE
 * Checked in by:  Joe;  Joe Spila
 * Change Description:  
 *   Updated status information sent to event log to be more specific on error information.
 * 
 * /////////////////////////////////////////////////////////////////////////////////////
 * 
 *    Rev 1.0   23 Jul 2007 15:22:38   tbair
 * Project:  SVObserver
 * Change Request (SCR) nbr:  597
 * SCR Title:  Upgrade Matrox Imaging Library to version 8.0
 * Checked in by:  tBair;  Tom Bair
 * Change Description:  
 *   Initial Check-in
 * 
 * /////////////////////////////////////////////////////////////////////////////////////
*/
