// ******************************************************************************
// * COPYRIGHT (c) 2007 by SVResearch, Harrisburg
// * All Rights Reserved
// ******************************************************************************
// * .Module Name     : SVMatroxStatusInformation
// * .File Name       : $Workfile:   SVMatroxStatusInformation.h  $
// * ----------------------------------------------------------------------------
// * .Current Version : $Revision:   1.0  $
// * .Check In Date   : $Date:   22 Apr 2013 15:27:22  $
// ******************************************************************************

#ifndef SV_MATROX_STATUS_INFORMATION_H
#define SV_MATROX_STATUS_INFORMATION_H

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SVMatroxTypedefs.h"

#include <string>

/**
@SVObjectName Matrox Status Information

@SVObjectOverview This class will be used to hold the status information generated by Matrox for each function call.

@SVObjectOperations This class will present empty, clear, and data extraction operators.

*/
class SVMatroxStatusInformation  
{
public:
	typedef long SVFunctionCode;
	typedef std::string SVFunctionString;
	typedef SVMatroxStatusCode SVStatusCode;
	typedef SVMatroxStatusString SVStatusString;

	SVMatroxStatusInformation();
	SVMatroxStatusInformation( const SVMatroxStatusInformation& p_rObject );

	virtual ~SVMatroxStatusInformation();

	bool empty() const;

	void clear();

	const SVMatroxStatusInformation& operator=( const SVMatroxStatusInformation& p_rObject );

	SVStatusString GetCompleteString() const;

	SVStatusCode m_StatusCode;
	SVStatusString m_StatusString;

	SVFunctionCode m_FunctionCode;
	SVFunctionString m_FunctionString;

	long m_StatusSubCodeCount;

	SVStatusCode m_StatusSubCode[ 3 ];
	SVStatusString m_StatusSubString[ 3 ];

};

#endif // SV_MATROX_STATUS_INFORMATION_H

