// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "svmaskeditor.h"

/////////////////////////////////////////////////////////////////////////////
// CSVMaskEditor

IMPLEMENT_DYNCREATE(CSVMaskEditor, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSVMaskEditor properties

long CSVMaskEditor::GetImageDIBHandle()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CSVMaskEditor::SetImageDIBHandle(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CSVMaskEditor::GetMaskOperator()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CSVMaskEditor::SetMaskOperator(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CSVMaskEditor::GetMaskData()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CSVMaskEditor::SetMaskData(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSVMaskEditor operations

void CSVMaskEditor::Refresh()
{
	InvokeHelper(DISPID_REFRESH, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CSVMaskEditor::DoEditMaskModal()
{
	long result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CSVMaskEditor::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
