#if !defined(AFX_SVMASKEDITOR_H__D8A623DE_F4E2_11D2_A796_00106F000C74__INCLUDED_)
#define AFX_SVMASKEDITOR_H__D8A623DE_F4E2_11D2_A796_00106F000C74__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSVMaskEditor wrapper class

class CSVMaskEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSVMaskEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc87c9b74, 0xe6dc, 0x11d2, { 0xa7, 0x7b, 0x0, 0x10, 0x6f, 0x0, 0xc, 0x7d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetImageDIBHandle();
	void SetImageDIBHandle(long);
	long GetMaskOperator();
	void SetMaskOperator(long);
	long GetMaskData();
	void SetMaskData(long);

// Operations
public:
	void Refresh();
	long DoEditMaskModal();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SVMASKEDITOR_H__D8A623DE_F4E2_11D2_A796_00106F000C74__INCLUDED_)
