//*****************************************************************************
/// \copyright (c) $YEAR$,$YEAR$ by Seidenader Maschinenbau GmbH
/// All Rights Reserved 
//*****************************************************************************
/// Class to generate a text form a ID (enum) and additional text list depending of language settings
//******************************************************************************
#pragma once

#pragma region Includes
//Moved to precompiled header: #include <map>
//Moved to precompiled header: #include <tchar.h>
//Moved to precompiled header: #include <boost\assign\std\map.hpp>
//Moved to precompiled header: #include <boost\assign\list_of.hpp>

#include "MessageTextEnum.h"
#pragma endregion Includes

namespace SvStl
{
	typedef std::map<MessageTextEnum, std::string> MessageTextMap;

	MessageTextMap g_MessageTextMap = boost::assign::map_list_of
	(Tid_Empty, _T(""))
	(Tid_Default, _T("%s"))
	(Tid_ErrorClass, _T("Error Nbr = %s, Program Cd = %s"))
	(Tid_XmlParserError, _T("%s, Error Code:%s, On line %s position %s"))
	(Tid_RestoreVariantError, _T("RestoreVariant returns: %s"))
	(Tid_TranslateVariantError, _T("TranslateVariant returns: %s"))
	(Tid_ToVariant_InvalidArgument, _T("Invalid Argument in function ToVariant"))

	(Tid_XML_UnexpectedType, _T("Unexpected TreeElementType in OnStartElement"))
	(Tid_XML_UnexpectedOnElementData, _T("Unexpected OnElementData"))
	(Tid_XML_InvalidPointer, _T("Invalid Pointer"))
	(Tid_XML_InvalidArrayElement, _T("Invalid ArrayElement in OnEndElement"))
	(Tid_XML_Error, _T("Error in Line, Column, Errornumber  : %s , %s , %s  : %s"))
	
	//SVObserver SVDLLToolLoadLibraryClass
	(Tid_ToolLoadError_ImageDef, _T("Error in MIL/HBITMAP function definitions."))
	(Tid_ToolLoadError_NoImageDef, _T("Neither MIL nor HBITMAP image functions are defined."))
	(Tid_ToolLoadError_BothSetsImagesDef, _T("Both sets of MIL and HBITMAP image functions are defined."))
	(Tid_ToolLoadError_BothImagesDef,  _T("Both MIL and HBITMAP image functions are defined."))
	(Tid_ToolLoadError_InFunctionDef, _T("Error in MIL/HBITMAP image functions definitions."))
	(Tid_ToolLoadError_SimpleTest, _T("SimpleTest failed."))
	(Tid_ToolLoadError_SimpleTestException, _T("SimpleTest failed - exception."))
	(Tid_ToolLoadError_DllStartup, _T("DLL Startup function failed."))
	(Tid_ToolLoadError_DllStartupException, _T("DLL Startup function failed.- exception"))
	(Tid_ToolLoadError_GetToolName, _T("DLL GetToolName function failed."))
	(Tid_ToolLoadError_GetToolNameException, _T("DLL GetToolName failed.- exception"))
	(Tid_ToolLoadError_GetToolVersion, _T("DLL GetToolVersion function failed."))
	(Tid_ToolLoadError_GetToolVersionException, _T("DLL GetToolVersion function failed - exception."))
	(Tid_GetProcAddressError_SimpleTest, _T("GetProcAddress failed SimpleTest"))
	(Tid_GetProcAddressError_GetToolName, _T("GetProcAddress failed GetToolName"))
	(Tid_GetProcAddressError_GetToolVersion, _T("GetProcAddress failed GetToolVersion"))
	(Tid_GetProcAddressError_RunTool, _T("GetProcAddress failed RunTool"))
	(Tid_GetProcAddressError_Startup, _T("GetProcAddress failed Startup"))
	(Tid_GetProcAddressError_ShutDown, _T("GetProcAddress failed ShutDown"))
	(Tid_GetProcAddressError_InitializeRun, _T("GetProcAddress failed InitializeRun"))
	(Tid_GetProcAddressError_UninitializeRun, _T("GetProcAddress failed UninitializeRun"))
	(Tid_GetProcAddressError_GetInputValueDefinitions, _T("GetProcAddress failed GetInputValueDefinitions"))
	(Tid_GetProcAddressError_DestroyInputValueDefinitionStructures, _T("GetProcAddress failed DestroyInputValueDefinitionStructures"))
	(Tid_GetProcAddressError_DestroyResultValueDefinitionStructures, _T("GetProcAddress failed DestroyResultValueDefinitionStructures"))
	(Tid_GetProcAddressError_SetInputValues, _T("GetProcAddress failed SetInputValues"))
	(Tid_GetProcAddressError_GetResultValues, _T("GetProcAddress failed GetResultValues"))
	(Tid_GetProcAddressError_GetMessageString, _T("GetProcAddress failed GetMessageString"))
	(Tid_GetProcAddressError_ValidateValueParameter, _T("GetProcAddress failed ValidateValueParameter"))
	(Tid_GetProcAddressError_GetResultValueDefinitions, _T("GetProcAddress failed GetResultValueDefinitions"))
	(Tid_GetProcAddressError_GetNumberOfInputImages, _T("GetProcAddress failed GetNumberOfInputImages"))
	(Tid_GetProcAddressError_GetResultImageDefinitions, _T("GetProcAddress failed GetResultImageDefinitions"))
	(Tid_GetProcAddressError_DestroyImageDefinitionStructure, _T("GetProcAddress failed DestroyImageDefinitionStructure"))
	(Tid_ToolLoadError, _T("Could not load DLL (LoadLibrary failed)."))
	(Tid_RunTool_Exception, _T("Exception in SVRunTool of some External Dll %s"))
	(Tid_SVInitializeRun_Exception, _T("Exception in SVInitializeRun in some External Dll %s"))

	///Defines for SVConfigurationObjects
	(Tid_CreateSFailed, _T("Create %s failed"))
	(Tid_NumberOfIosMissing, _T("the Number of Ios Entries is missing."))
	(Tid_IOEntryIsMissing, _T("an IO Entry is missing."))
	(Tid_CreationOfPPQFailed,  _T("The PPQ Object could not be created."))
	(Tid_InputIsMissing, _T("an Input tag is missing"))
	(Tid_MsgIOTypeIsMissing, _T("an IO Type is missing"))
	(Tid_MsgIONameIsMissing, _T("an Item Name is missing"))
	(Tid_MsgPPQPOsitionIsMissing, _T("a PPQ Position is missing"))
	(Tid_MsgRemoteIndexIsMissing, _T("a Remote Index is missing"))

	(Tid_ActivatingDiskProtection, _T("Activating disk protection.\nAfter the next restart C:\\ will be protected"))
	(Tid_DeactivatingDiskProtection, _T("Deactivating disk protection.\nAfter the next restart C:\\ will not be protected"))
	(Tid_DiskProtectionRemainsActive, _T("Disk protection will remain active.\n"))
	(Tid_DiskProtectionRemainsInactive, _T("Disk protection will remain inactive."))
	(Tid_CouldNotExecuteFormatString, _T("could not execute '%s'"))

	//RangeValue
	(Tid_RangeValue_EmptyString, _T( "Empty String in %s." ))
	(Tid_RangeValue_WrongRange, _T( "%s must between %s and %s." ))
	(Tid_ErrorUnknownEnum, _T( "Unknown enum" ))
	(Tid_FailHigh, _T("Fail High"))
	(Tid_FailLow, _T("Fail Low"))
	(Tid_WarnHigh, _T("Warn High"))
	(Tid_WarnLow, _T("Warn Low"))
	(Tid_IsLessThan, _T("ERROR:\n%s\nis less than\n%s"))
	(Tid_IsInvalidRef, _T("ERROR:\n%s: %s\nis an invalid reference."))

	(Tid_ErrorInitMonitorListInSharedMemory, _T("InitMonitorListInSharedMemory - Not enough memory"))
	(Tid_ErrorWriteMonitorListNoSharedMemory, _T("WriteMonitorListToSharedMemory - No Shared memory"))
	(Tid_ErrorReleaseProductNoReaderLock, _T("ReleaseProduct - No Reader Lock found"))
	(Tid_RingBuffer_Depth_Invalid_Value, _T( "RingBuffer Depth has to be between %s and %s, current %s" ))
	(Tid_Error_NoFontFileSpec, _T("No Font File Specified"))
	(Tid_Error_FontFileNotExist, _T( "Font File Does Not Exist: %s" ))
	(Tid_Error_FontFileEmpty, _T( "Font File Empty: %s" ))
	(Tid_SVAcquisitionClass_GetNextIndex, _T( "SVAcquisitionClass::GetNextIndex-Name=%s"))
	(Tid_ArchiveTool_PathEmpty, _T("Archive Path is empty"))
	(Tid_ArchiveTool_CreateFileFailed, _T("Create Archive File \"%s\" Failed"))
	(Tid_ArchiveTool_CreatePathFailed, _T("Create Archive Path \"%s\" Failed"))
	(Tid_ArchiveTool_WriteToFileFailed, _T("Write to Archive File failed"))
	(Tid_ArchiveTool_AllocImageFailed, _T("Allocate Image Buffer failed: %s"))
	(Tid_PathFileNotFound, _T("Path/File not found:  %s"))
	(Tid_BarCode_UnableToRead, _T("Bar Code Analyzer was unable to read\nthe match string from file. Check the\nanalyzer settings for proper match string."))
	(Tid_BarCode_UnableToSave, _T("Bar Code Analyzer was unable to save\nthe match string to file. Check the\nanalyzer settings for proper match string."))
	(Tid_BlobAnalyzer_ResultCreationFailed, _T("Creation of Blob Analyzer Result Failed"))
	(Tid_CreationFailed, _T("Creation of %s Failed"))
	(Tid_CreationOf2Failed, _T("Creation of %s \"%s\" failed."))
	(Tid_Command_StartSvimConfig, _T("Informational - Starting PutSVIMConfig"))
	(Tid_Command_EndSvimConfig, _T("Informational - Ending PutSVIMConfig"))
	(Tid_ErrorMIL, _T("%s - An error has occurred, MIL error code = %s, MIL error Text = %s"))
	(Tid_ErrorGettingPPQ, _T( "Error getting PPQ." ))
	(Tid_ErrorGettingInputObjectList, _T( "Error getting input object list." ))
	(Tid_ErrorFillingInputs, _T( "Error filling inputs." ))
	(Tid_ErrorGettingPPQCount, _T( "Error getting PPQ count." ))
	(Tid_Acquisition_SourceInformationFailed, _T("Failed to get acquisition source information!"))
	(Tid_TooManyVariables, _T("%s\nToo many variables."))
	(Tid_EquationParserError, _T("%s\nSyntax Error at position %s"))
	(Tid_InvalidData, _T("Invalid Data"))
	(Tid_Error_NoResultObject, _T("Cannot find the Result Object"))
	(Tid_ImageClass_DestroyError, _T("Failed to destroy the image object!"))
	(Tid_GetParentImageHandleError, _T("Cannot Get Indexed Child Image Handle"))
	(Tid_DisplayedImageIsUnavailable, _T("Displayed image is unavailable"))
	(Tid_InspThreadGetResultImageIndexError, _T( "Inspection Thread-Name=%s-Error in getting Result Image Index" ))
	(Tid_ErrorNotAllDataItemsFound, _T("Not All Data List items found"))
	(Tid_ErrorNotAllImageItemsFound, _T("Not All Image List items found"))
	(Tid_ErrorProcessNotifyLastInspected, _T("ProcessNotifyWithLastInspected - %s"))
	(Tid_Unknown, _T("Unknown"))
	(Tid_ErrorLockingInputImageRequests, _T( "Error locking input image requests." ))
	(Tid_ErrorLockingInputRequests, _T( "Error locking input requests." ))
	(Tid_ErrorRemovingAllInputRequests, _T( "Error removing all input requests." ))
	(Tid_ErrorRemovingAllInputImageRequests, _T( "Error removing all input image requests." ))
	(Tid_ErrorUnlockingInputImageRequests, _T( "Error unlocking input image requests." ))
	(Tid_ErrorUnlockingInputRequests, _T( "Error unlocking input requests." ))
	(Tid_IPDoc_NoCameraColorAttached, _T("Color camera not attached to this IPDoc"))
	(Tid_ErrorGettingTimeStamp, _T( "Error getting time stamp." ))
	(Tid_ProcessTrigger, _T("ProcessTrigger - %s"))
	(Tid_ErrorNotAllRejectConditionItemsFound, _T("Not All Reject Condition List items found"))
	(Tid_ReleaseProduct, _T("Release Product - %s"))
	(Tid_ErrorCopyLastInspectedToReject, _T("Copy Last Inspected To Reject failed"))
	(Tid_CommitSharedMemory, _T("Commit Shared Memory - %s"))
	(Tid_SVIODoc_ClosingImpossible, _T("Invalid Operation!\nThe IO Dialog can not be closed without\nclosing the whole configuration."))
	(Tid_SVIPDoc_ClosingImpossible, _T("Invalid Operation!\nIf You wish to remove this inspection\nGo to the Edit menu and Select Edit Configuration."))
	(Tid_SVIPDoc_GoIntoRegTestFailed, _T("Inspection is unable to go into Regression Test Mode.  There is an unknown error with the inspection."))
	(Tid_ErrorDetachingInput, _T( "Error detaching input." ))
	(Tid_ColorToolMustBeFirstMessage, _T( "A Color Tool must ALWAYS be\n the first tool on a color system." ))
	(Tid_LightReference_NotAvailable, _T("Light Reference not available for %s"))
	(Tid_LUT_NotAvailable, _T("LUT not available for camera(s)"))
	(Tid_LUT_ShouldOverwriteAllBands, _T("Selecting this option will overwrite all bands with the currently displayed LUT information. Continue?"))
	(Tid_Error_WrongCameraModel, _T("Wrong camera model: Expected %s, Current %s"))
	(Tid_Error_WrongCameraVendor, _T("Wrong camera vendor: Expected %s, Current %s"))
	(Tid_CreateBufferFailed, _T("Failed to create an image buffer!"))
	(Tid_CreateImageChildBuffer_parent, _T("\"%s\" was located partially or completely outside of "
	"the bounds of \"%s\".\nIt has been moved and/or resized "
	"to fit in the bounds.\nThis configuration should be "
	"saved to prevent this message from appearing again."))
	(Tid_CreateImageChildBuffer_child, _T("\"%s\" was located partially or completely outside of "
	"the bounds of its parent image.\nIt has been moved "
	"and/or resized to fit in the bounds.\nThis configuration "
	"should be saved to prevent this message from appearing "
	"again."))
	(Tid_CreateImageChildBuffer, _T("A child buffer was located partially or completely outside "
	"of the bounds of its parent image.\nIt has been moved "
	"and/or resized to fit in the bounds.\nThis configuration "
	"should be saved to prevent this message from appearing "
	"again."))
	(Tid_MatroxImage_UnableToFindFile, _T( "Unable to locate image file:\n%s\n\nBrowse..." ))
	(Tid_UnKnownFileFormat, _T("Unknown File Format!"))
	(Tid_FailedToLoadImage, _T("Failed to load an image!"))
	(Tid_FailedToSaveImage, _T("Unable to Save Image"))

	//Custom Filter 2
	(Tid_DataInvalidKernelSize, _T("The Kernel array size [%s] does not match the size of the Kernel Width [%s] and Height [%s]"))
	(Tid_DataInvalidKernelWidth, _T("The Kernel Width is not valid [%s], it must be odd and be between the limits including 1 and %s"))
	(Tid_DataInvalidKernelHeight, _T("The Kernel Height is not valid [%s], it must be odd and be between the limits including 1 and %s"))
	(Tid_DataInvalidNormalizationFactor, _T("The Normalization Factor is not allowed to be 0 or negative"))
	(Tid_ExportFailed, _T("Custom filter export failed"))
	(Tid_ImportFailed, _T("The Custom Filter file [%s] could not be imported.\n%s"))
	(Tid_XmlFormatInvalid, _T("The XML format is invalid."))
	(Tid_VersionMismatch, _T("Version mismatch."))
	(Tid_ImportFailedDataInvalid, _T("Custom filter import failed, Kernel data is invalid."))

	(Tid_True, _T("TRUE"))
	(Tid_False, _T("FALSE"))
	(Tid_ConditionalValidated, _T("Conditional Equation Validated Successfully\n Condition = %s"))
	(Tid_FormulaValidated, _T("Formula Validated Successfully\n Value = %s"))
	(Tid_Error_InvalidFormula, _T("An Invalid Formula has been detected.\nThe Formula must be valid to exit this dialog."))
	(Tid_Error_CreationFilterFailed, _T("Creation of Filter Failed"))
	(Tid_Error_ToolPositionError, _T("Changing image source has placed the tool outside of the selected source image.  Please either: "
		"select a new image source, resize the image source to contain this tool, or resize/position this tool to fit on the source image."))
	(Tid_RingBuffer_Depth_Invalid_ValueString, _T( "RingBuffer Depth has to be between %s and %s, current %s" ))
	(Tid_RingBuffer_ImageIndex_Invalid_ValueString, _T( "RingBuffer Image Index %s value invalid." ))
	(Tid_Error_NoDeviceContext, _T("No device context available!"))
	(Tid_Lpt_WrongState, _T("Select Line In wrong State"))
	(Tid_Sax_ConInitializeExFailed, _T("CoInitializeEx Failed"))
	(Tid_UnknowThread, _T( "Unknown Thread" ))

	//MatroxGigE
	(Tid_MatroxGigE_Connect_FindCameraError, _T("HandleConnect - FindCamera Error (%s) - Device %s"))
	(Tid_MatroxGigE_Connect_GetDigitizerError, _T("HandleConnect - GetDigitizer Error (%s) - Device %s"))
	(Tid_MatroxGigE_Connect_AllocError, _T("HandleConnect - AllocDigitizer Error (%s) - Device %s"))
	(Tid_MatroxGigE_Connect_ReadError, _T("HandleConnect - ReadCameraFormat Error (%s) - Device %s"))
	(Tid_MatroxGigE_Connect_CreateError, _T("HandleConnect - CreateAcquisitionBuffers Error (%s) - Device %s"))
	(Tid_MatroxGigE_Connect_ReloadError, _T("HandleConnect - Reload Camera Parameters Error (%s) - Device %s"))
	(Tid_MatroxGigE_Connect_StartDigitizerError, _T("HandleConnect - StartDigitizer Error - Device %s"))
	(Tid_MatroxGigE_Disconnect_FindCameraError, _T("HandleDisconnect - FindCamera Error (%s) - Device %s"))
	(Tid_MatroxGigE_Disconnect_GetDigitizerError, _T("HandleDisconnect - GetDigitizer Error (%s) - Device %s"))
	(Tid_MatroxGigE_Disconnect, _T("CameraPresentCallback - Disconnect - Device %s"))
	(Tid_MatroxGigE_Connect, _T("CameraPresentCallback - Connect - Device %s"))
	
	(Tid_FileCamera_NoImageFile, _T("E: FileAcquisition::No Image File to Load, possible Invalid or Empty Directory %s"))
	(Tid_FileCamera_LoadFailed, _T("E: FileAcquisition::Unable to Load Image File %s"))
	(Tid_FileAcquisition_FormatError, _T("E: FileAcquisition::CopyImage - Error in Format"))
	(Tid_ObjectBuilder_SetObjectValueError, _T("SVObjectBuilder::SetObjectValue Error:\n Set Object Member Value failed!"))
	(Tid_ErrorUsedPreviouslyForSec, _T("This was previously used for .sec files."))

	//ParseError
	(Tid_ParseError_NameMustNotContainKeyword, _T("Parser Error:\nName expression expected, valid names must not contain keywords!"))
	(Tid_ParseError_OutOfMemory, _T("Parser Error:\nOut of memory!"))
	(Tid_ParseError_NameExpressionExpected, _T("Parser Error:\nName expression expected!"))
	(Tid_ParseError_OwnerNotExist, _T("Parser Error:\nOwner doesn't exist, cannot access member!"))
	(Tid_ParseError_UnexpectedMember, _T("Parser Error:\nUnexpected member access operator!"))
	(Tid_ParseError_CannotReadGuid, _T("Parser Error:\nCannot read GUID!"))
	(Tid_ParseError_ExpressionExpected, _T("Parser Error:\nExpression expected!"))
	(Tid_ParseError_UnknownExpression, _T("Parser Error:\nUnknown expression!"))
	(Tid_ParseError_UnexpectedEndOfCommand, _T("Parser Error:\nUnexpected end of command!"))
	(Tid_ParseError_CriticalErrorRemovingDependencies, _T("Critical Error removing external dependencies"))
	(Tid_ParseError_UnexpectedEndOfParse, _T("ParserState: READ_STRING\nParser Error, unexpected end of parse string while reading string..."))
	(Tid_ParseError_UnexpectedEndOfName, _T("ParserState: READ_NAME_STRING\nParser Error, unexpected end of name string while parsing ..."))
	(Tid_ParseError_EmptyToken, _T("ParserState: READ_GUID_STRING\nParser Error, empty token found..."))
	(Tid_ParseError_GuidCannotEvaluated, _T("ParserState: READ_GUID_STRING\nParser Error, GUID expression cannot be evaluated..."))
	(Tid_ParseError_NameOperandExpected, _T("Parser Error:\nName operand expected!"))
	(Tid_ParseError_OperatorExpected, _T("Parser Error:\nOperator, expected!"))
	(Tid_ParseError_OperandExpected, _T("Parser Error:\nObject operand, class operand or embedded operand expected!"))
	(Tid_ParseError_CommandTerminationExpected, _T("Parser Error:\nCommand termination expected!"))
	(Tid_ParseError_TooManyExpressions, _T("Parser Error:\nToo many expressions found!"))
	(Tid_ParseError_ClassOperandExpected, _T("Parser Error:\nClass operand expected!"))
	(Tid_ParseError_OperatorOperand, _T("Parser Error:\nOperator operand expected!"))
	(Tid_ParseError_ObjectOperandExpected, _T("Parser Error:\nObject operand expected!"))
	(Tid_ParseError_UnableToReadInputList, _T("Parser Error:\nUnable to read input list!"))
	(Tid_ParseError_CommandTerminationOrObjectMemberExpected, _T("Parser Error:\nCommand termination or object member definition expected!"))
	(Tid_ParseError_NoValidObjectOwner, _T("Parser Error:\nNo valid object owner given!"))
	(Tid_ParseError_WrongEmbeddedValues, _T("Parser Error:\nWrong embedded values!"))
	(Tid_ParseError_CannotConstructObject, _T("Parser Error:\nCannot construct new object!"))
	(Tid_ParseError_ObjectRequired, _T("Parser Error:\nObject required for Member!"))
	(Tid_ParseError_ValuesExpected, _T("Parser Error:\nValues expected!"))
	(Tid_ParseError_NoValidObject, _T("Parser Error:\nNo valid object given!"))
	(Tid_ParseError_SetObjectMemberFailed, _T("Parser Error:\nSet Object Member Value failed!"))
	(Tid_Error_ScriptParseFailed, _T("%s parse was not successful"))

	//SVObserver
	(Tid_SVObserver_CannotRun_WrongModelNumber, _T( "Configuration cannot enter Run.  The current configuration hardware does not match system hardware. "
	"The system's Model Number is ( Model # %s %s %s %s ). Please verify that the shown model number is correct and contact your system administrator."))
	(Tid_SVObserver_InitializationFailure, _T("Initialization failure (Model Number %s):\n%s"))
	(Tid_SVObserver_ModelNumberInvalid, _T("The model number specified in OEMINFO.INI is invalid."))
	(Tid_SVObserver_AuthorizationFailed_Modification, _T( "Authorization Failed.\n\nUtility Modification requires 'User Manager' privilege." ))
	(Tid_SVObserver_AuthorizationFailed_Execution, _T("Authorization Failed.\n\nUtility Execution requires 'User Manager' privilege."))
	(Tid_SVObserver_MatroxGigELicenseNotFound, _T("Matrox GigE License not found"))
	(Tid_SVObserver_MatroxLicenseNotFound, _T("Matrox License not found"))
	(Tid_SVObserver_WrongVersionNumber, _T( "This configuration was created by SVObserver %s.\nYou are currently running SVObserver %s.\n"
		"This configuration version may be incompatible with\nthe version of SVObserver that you are running.\nAre you sure you wish to continue ?" ))
	(Tid_SVObserver_ConfigurationLoadFailed, _T( "The configuration could not successfully load.\nhr = %s.\n"))
	(Tid_SVObserver_SecurityFileLoadFailed, _T("Security File Failed to Load\n Using Default Security"))
	(Tid_SVObserver_WrongPathnameEntered, _T("Invalid path or file name found\n\nCheck your inputs and try it again!"))
	(Tid_SVObserver_RegisterClassObjectsFailed, _T( "(hr=0x%s), Unable to register class objects. COM interface ISVCommand unavailable."))
	(Tid_SVObserver_RegisterClassObjectsFailed_Question, _T( "(hr=0x%s), Unable to register class objects. COM interface ISVCommand unavailable.\nDo you want to exit?"))
	(Tid_SVObserver_OleInitFailed, _T( "OLE initialization failed.  Make sure that the OLE libraries are the correct version."))
	(Tid_CanGoOnlineFailure_Trigger, _T( "Configuration cannot enter Run.  There is an "
			"unknown error with Trigger %s when the system attempted to enter Run." ))
	(Tid_CanGoOnlineFailure_Acquisition, _T( "Configuration cannot enter Run.  Cannot connect to camera %s when the system attempted to enter Run." ))
	(Tid_CanGoOnlineFailure_InspectionTool, _T("Configuration cannot enter Run.\n Error with \"%s\" : %s"))
	(Tid_CanGoOnlineFailure_Inspection, _T( "Configuration cannot enter Run.  There is an "
							"unknown error with an inspection %s when the system attempted to enter Run." ))
	(Tid_CanGoOnlineFailure_ConditionalOutput, _T( "Configuration cannot enter Run.  There is an "
							"unknown error by resolving the coditionalOutputs when the system attempted to enter Run." ))
	(Tid_GoOnlineFailure_RecycleProduct, _T( "Configuration cannot enter Run.  There is an "
						"unknown error with a PPQ when it attempted to recycle a product when the system was going online." ))
	(Tid_GoOnlineFailure_RecycleProductId, _T( "Configuration cannot enter Run.  There is the "
						"error %s with a PPQ when it attempted to recycle a product when the system was going online." ))
	(Tid_GoOnlineFailure_Inspection, _T( "Configuration cannot enter Run.  There is an "
						"unknown error with Inspection %s when the system was going online." ))
	(Tid_GoOnlineFailure_Acquisition, _T("Configuration cannot enter Run.  Cannot reach camera %s when the system was going online." ))
	(Tid_GoOnlineFailure_Trigger, _T( "Configuration cannot enter Run.  There is an "
						"unknown error with Trigger %s when the system was going online." ))
	(Tid_GoOnlineFailure_InternalTrigger, _T( "Configuration cannot enter Run.  There is the "
						"error %s with enable internal Trigger when the system was going online." ))
	(Tid_GoOnlineFailure_CreatePPQThread, _T( "Configuration cannot enter Run.  There is the "
						"error %s by creating the PPQ Thread." ))
	(Tid_GoOnlineFailure_CreateTimerThread, _T( "Configuration cannot enter Run.  There is the "
						"error %s by creating the timer Thread." ))
	(Tid_GoOnlineFailure_InvalidPointerConfig, _T( "Configuration cannot enter Run.  Invalid pointer of configuration or mainWnd." ))
	(Tid_GoOnlineFailure_RaidBits, _T( "Configuration cannot enter Run.  Error by setting of raid bits." ))
	(Tid_GoOnlineFailure_ModuleReadyOutput, _T( "Configuration cannot enter Run.  Cannot write to module ready output." ))
	(Tid_ErrorNotEnoughDiskSpace, _T("Unable to set monitor list for %s - Not enough Disk Space Available"))
	(Tid_GoOnlineFailure_SendCameraParam, _T( "Configuration cannot enter Run.  There is an "
						"unknown error by sending camera parameter when the system was going online." ))
	(Tid_AmountOfSystemMemoryText, _T("Amount of physical memory = %s"))
	(Tid_Version, _T("\nVersion %s"))
	(Tid_ConfigLoadTime, _T("%s\nload time %s ms"))
	(Tid_UserQuestionCloseConfig, _T("Are you sure you want to close the current SVObserver application  %s?\n\nALL CURRENT RUNNING INSPECTIONS WILL BE STOPPED!"))
	(Tid_UserQuestionSaveChanges, _T("Save changes to %s?"))
	(Tid_UnableConfig, _T("Unable to %s configuration %s !"))
	(Tid_Load, _T("load"))
	(Tid_Save, _T("save"))
	(Tid_GoOnlineTime, _T("%s\nGoOnline time %s ms"))

	(Tid_Camera_UseQuestion, _T("Would you like to use this camera file for all camera choices?"))
	(Tid_Config_SwitchResetQuestion, _T("By switching the system (product) the camera, trigger, inspection and ppq data will be reset, do you wish to continue?"))
	(Tid_Config_SwitchInvalidQuestion, _T("By switching the system (product) the camera files will become invalid, do you wish to continue?"))
	(Tid_Config_InspectionImportFailed, _T("Inspection Import failed. Error = %s"))
	(Tid_Config_CameraFileNameInvalid, _T("Camera file name is invalid %s"))
	(Tid_Config_CameraFileInvalid, _T("Camera file is invalid %s"))
	(Tid_Error_NoMilHostBuffer, _T("No Mil Host Buffer Pointer"))
	(Tid_Error_MilImageTypeInvalid, _T("MIL Image Type Not 8 Bit Unsigned: %s"))
	(Tid_Error_FontNotMfoExt, _T( "Font File Requires '.mfo' Extension: %s" ))
	(Tid_Error_NoFontConstraintsFileSpec, _T("No Font Constraints File Specified"))
	(Tid_Error_FontConstraintsRequiredMfoExt, _T( "Font Constraints File Requires '.mfo' Extension: %s" ))
	(Tid_Error_FontConstraintsFileNotExist, _T( "Font Constraints File Does Not Exist: %s" ))
	(Tid_Error_FontConstraintsFileEmpty, _T( "Font Constraints File Empty: %s" ))
	(Tid_Error_NoFontControlsFileSpec, _T("No Font Controls File Specified"))
	(Tid_Error_FontControlsRequiredMfoExt, _T( "Font Controls File Requires '.mfo' Extension: %s" ))
	(Tid_Error_FontControlsFileNotExist, _T( "Font Controls File Does Not Exist: %s" ))
	(Tid_Error_FontControlsFileEmpty, _T( "Font Controls File Empty: %s" ))
	(Tid_ImportInspectionError, _T("Inspection was exported using SVObserver %s. \tThis is incompatible with SVObserver %s."))
	(Tid_Error_InvalidThresholdValue, _T("Invalid Threshold Value"))
	(Tid_Pattern_Model2Large, _T("Model is larger than the ROI of the Window Tool."))
	(Tid_Pattern_DontCare2Small, _T("The don't care image is to small. It must have at least the size of the model."))
	(Tid_Pattern_Invalid_ShouldLeave, _T("Pattern Model is invalid. Do you want to change Model (Yes) or leave dialog (No)?"))
	(Tid_ErrorGettingInputs, _T( "Error getting inputs." ))
	(Tid_ErrorFindingPPQEntries, _T( "Error finding PPQ entries." ))
	(Tid_InvalidReference, _T("%s: Invalid reference"))

	(Tid_RegressionTest_NoBmpFileSelected, _T("Selection Error:  A .bmp file must be selected."))
	(Tid_RegressionTest_WrongListSize, _T("Selection Error:  Lists must be the same size.  Please select again."))
	(Tid_RegressionTest_NoFileSelected, _T("Selection Error in %s: \"Use single file\" is selected for one of the cameras but a file was not selected. Select again?"))
	(Tid_RegressionTest_WrongFormat, _T("Selection Error in %s: \"Use list of files\" selected, but the file name does not match\n the acceptable format (<file name>_<sequence number>.bmp). Select again?"))
	(Tid_RegressionTest_NoFilesSelected, _T("Selection Error:  \"No files\" selected.  Select again?"))
	(Tid_RegressionTest_FileNotExist, _T("Selection Error in %s:  File does not exist.  Select again?"))
	(Tid_RegressionTest_EmptyDirectory, _T("Selection Error in %s:  Directory has no .bmp files.  Select again?"))
	(Tid_RemoteOutput_TriggerCountDeleteError, _T("Trigger Count Cannot Be deleted"))
	(Tid_RemoteOutput_DeletingOutput, _T("Are You Sure you want to delete this Output?"))
	(Tid_RemoteOutput_DeletingAllOutput, _T("Are you sure you want to delete All Entries for %s"))
	(Tid_ResultView_InitFailed, _T("Failed to init inspection result view!"))
	(Tid_StatTool_ResultFailed, _T("Creation of Statistics Result Failed"))

	(Tid_InvalidImagePath, _T("Invalid Keywords in Archive Image Path."))
	(Tid_InvalidDrive, _T("Invalid drive: %s"))
	(Tid_InvalidFileName, _T("Invalid Keywords in Archive Filename/Path."))
	(Tid_FileName_Exists, _T("%s already exists.\nDo you want to replace it?"))
	(Tid_Error_you_have_Selected_X_Must_less_then_Y, _T("Error: You have selected %s for the Max Images count. The image count must be less then %s"))
	(Tid_ArchiveTool_WarningMaxImages, _T("WARNING: You have selected %s for the Max Images count"))
	(Tid_AP_NotEnoughImageMemoryInChangeMode, _T("There is not enough Available Archive Image Memory for %s images in Change Mode. Available\nArchive Image Memory is the result of the selected images and the Max Images number.\nThe selection will be reset."))
	(Tid_AP_NotEnoughImageMemoryToSelect, _T("Not enough Archive Image Memory to select %s"))
	(Tid_AP_NotEnoughMemoryPleaseDeselectImage, _T("Not enough Archive Image Memory for the images selected. Please deselect some images."))
	(Tid_AP_NotEnoughMemoryInChangeMode, _T("There is not enough Available Archive Image Memory for your selection in Change Mode.\nAvailable Archive Image Memory is the result of the selected images and the Max Images number."))
	(Tid_AP_NotEnoughMemoryPleaseDeselect, _T("Not enough Available Archive Image Memory. Please deselect some\nimages, decrease \"Max Images\" or change \"When to archive\" mode."))
	(Tid_Threshold_OutOfRange, _T("Out of Range!\n(0 ... 255)"))
	(Tid_CriticalUnableToConnectTo, _T("Unable to connect to %s"))
	(Tid_UnknownString, _T("<Unknown>"))
	(Tid_Error_DuplicateEmbeddedId, _T("Error - Duplicate Embedded ID found"))
	(Tid_Error_CannotAddInputRequest, _T("Cannot Add Input Request.\nPlease contact technical support specialist."))
	(Tid_Error_CannotAddInputRequestMarker, _T("Cannot Add Input Request Marker.\nPlease contact technical support specialist."))
	(Tid_Error_CannotRunOnce, _T("Cannot Run Once.\nPlease contact technical support specialist."))
	(Tid_ErrorIn, _T("Error in %s"))
	(Tid_Error_NoAnalyzerDetails, _T("No Analyzer Details available!\nTry to select an Analyzer first.\nNOTICE: Some Tools don´t have an Analyzer!"))
	(Tid_Error_AnalyzerCreationFailed, _T("Creation of Analyzer Failed"))
	(Tid_Error_AnalyzerInstantiationFailed, _T("Instantiation of Analyzer Failed"))
	(Tid_LinearSpecial_OrientationVertical, _T("Tool profile orientation is at vertical.  By turning rotation on the profile orientation will be set to horizontal. Do you wish to continue"))
	(Tid_LinearSpecial_IsRotated, _T("Tool is currently rotated.  By turning off rotation the figure will be drawn at a rotation angle of 0. Do you wish to continue"))
	(Tid_MaskPage_StartOCXFailed, _T("Static Mask Editor OCX Failed to Start"))
	(Tid_Error_CannotOpenFile, _T("Cannot open file %s !"))
	(Tid_Error_CannotOpenTADlg, _T("Unable to open Tool Adjustment Dialog!"))
	(Tid_UnableStart_Utility, _T("Unable to start %s\n(%s).\n\nCheck Utility Properties."))
	(Tid_SetClipboardDataFailed, _T( "Setting the data into the clipboard failed." ))
	(Tid_ClipboardDataConverionFailed, _T( "The clipboard data conversion failed." ))
	(Tid_ClipboardMemoryFailed, _T( "Clipboard memory allocation failed." ))
	(Tid_GetClipboardDataFailed, _T( "Failed to retrieve the clipboard data." ))
	(Tid_ToolInvalid, _T( "The tool to be copied is invalid." ))
	(Tid_Clipboard_VersionMismatch, _T( "The current SVObserver Version does not match the version coming from the clipboard." ))
	(Tid_ColorToolInsertFailed, _T( "A color tool cannot be inserted into a non-color system." ))
	(Tid_NonColorToolInsertFailed, _T( "A color tool must always be the first tool in a color system." ))
	(Tid_RenameError_DuplicateName, _T("A duplicate name was found for the item being renamed\n%s"))
	(Tid_ErrorInReset, _T("Error in Reset"))
	(Tid_InValidNewExtents, _T("The new extents for the %s are not valid"))
	(Tid_MilVersion_Error, _T("This version of SVObserver will not run with the installed MIL library. SVObserver needs MIL %s. The installed version is %s"))
	(Tid_StatToolInvalidVariable, _T("%s\nError - The Selected Variable To Monitor does not exist."))
	(Tid_PatModelSizeErr, _T("Invalid Model Size"))
	(Tid_PatInvalidFilename, _T("Not a Valid Model file"))
	(Tid_DontCareInvalidFilename, _T("Not a Valid Don't Care file"))
	(Tid_DontCareImage_LoadFailed, _T("Load of don't care image failed."))
	(Tid_PatAllocModelFailed, _T("Pattern Model Allocation Failed."))
	(Tid_PatAllocFailed, _T("Pattern image Allocation Failed."))
	(Tid_PatAdditionalCandidatesErr, _T("Invalid Additional Candidates Value (range is 1 to 100)"))
	(Tid_PatCandidateSpaceErr, _T("Invalid Candidate Spacing Min Value (range is 1.0 to 100.0)"))
	(Tid_PatPreliminaryAcceptanceThresholdErr, _T("Invalid Preliminary Acceptance Threshold Value (range is 1.0 to 100.0)"))
	(Tid_Security_GainedAccess, _T("%s - Gained Access"))
	(Tid_Security_Login, _T("Login"))
	(Tid_Security_Access, _T("Access - %s"))
	(Tid_Security_UserNoRights, _T("User Does Not Have Rights to This Function"))
	(Tid_Security_Access_Granted, _T(" User: %s\n Gained Access to - %s"))
	(Tid_Security_Access_Denied, _T(" User: %s\n Attempt to Access - %s"))
	(Tid_Security_Disabled, _T("Security Disabled"))
	(Tid_OS_Error_Message, _T("OS Error Number: %s [%s]\nMessage: %s"))

	(Tid_Drive_Full, _T(" %s - drive is full."))
	(Tid_ConditionalValue_Invalid, _T("The conditional value of tool \"%s\" is invalid.")) 

	(Tid_TableColumnName_NotUnique, _T("The name \"%s\" is used already by another column.\nThe name must be unique."))
	(Tid_TableColumnName_Empty, _T("The column name must not be empty and is not allowed to contain only invalid characters."))
	(Tid_TableColumn_AddingFailed, _T("Adding a column failed. Error number %s."))
	(Tid_TableColumn_MovingFailed, _T("Moving a column failed. Error number %s."))
	(Tid_TableColumn_RemovingFailed, _T("Removing a column failed. Error number %s."))
	(Tid_TableColumn_RenamingFailed, _T("Renaming a column failed. Error number %s."))
	(Tid_TableColumn_TooManyEquation, _T("Too many equation for columns. Max number = %s. Delete the last one."))
	(Tid_TableObject_CreateFailed, _T("Creating the table object in the table tool failed."))
	(Tid_TableObject_Nullptr, _T("Table object in the table tool is a nullptr."))
	(Tid_TableObject_columnValueMapInvalid, _T("The columnValueMap in the table object has invalid entries."))
	(Tid_TableObject_columnValue_NoFreeGUID, _T("Too many column equation, no free GUID for the column value objects."))
	(Tid_TableObject_createColumnValueObjectFailed, _T("Creating a value object in the table object failed."))
	(Tid_TableObject_MaxRowWrongValue, _T("Maximum rows must be between %s and %s, current = %s."))
	(Tid_TableCopy_Nullptr, _T("No Source Table object is selected."))
	(Tid_UnknownCommitError, _T("Unknown Commit or Reset error %s."))
	(Tid_UnknownCommandError, _T("Unknown Command error %s."))

	(Tid_MoreThanPercentUsed, _T("\nMore than %s% [%s%] has been used."))
	(Tid_ConnectTableSourceFailed, _T("Connect Table Source \"%s\" with \"%s\" failed."))
	(Tid_ConnectFailed, _T("Connect \"%s\" failed."))
	(Tid_ConnectInputFailed, _T("Connect Input failed."))
	(Tid_NoValidTableConnected, _T("There is no valid table connected to the tool."))
	(Tid_Error_CreationAnalyzerFailed, _T("Creation of Analyzer Failed"))
	(Tid_Error_SetTableAnalyzerData, _T("Set from Table Analyzer Data failed: %s"))
	(Tid_NoValidColumnConnected, _T("There is no valid column to the analyzer connected."))
	(Tid_ExcludeHighMustBeHigher, _T("Exclude High must be higher than Exclude Low."))
	(Tid_LinkedValue_ValidateStringFailed, _T("Set of parameter \"%s\" failed: Invalid object name or value type."))
	(Tid_ValueObject_ValidateStringFailed, _T("Set value \"%s\" to parameter \"%s\" failed: Invalid string."))
	(Tid_SetEmbeddedValueFailed, _T("Setting of an embedded parameter failed: [%s]"))
	(Tid_ValidateValue_InvalidElementInVariantArray, _T("Validate Value failed: Invalid element in VariantArray: %s"))
	(Tid_ValidateValue_ArraySizeInvalid, _T("Validate Value failed: Array Size must greater than zero."))
	(Tid_UnexpectedError, _T("An unexpected error ocurred."))
	
	(Tid_FailedtoStart, _T("Failed to start %s"))
	(Tid_SocketInvalid, _T("Invalid socket Error: %s"))
	(Tid_InvalidCommand, _T("Invalid Command received: %s"))
	(Tid_CannotOpenReader, _T("Cannot open Reader"))
	(Tid_InvalidArguments, _T("Invalid arguments: %s"))
	(Tid_InvalidMonitorlist, _T("Invalid monitor list name: %s"))
	(Tid_RejectNotFound, _T("Reject not found"))
	(Tid_ProductNotFound, _T("Product not found"))
	(Tid_CreateChildBufferFailed, _T("Create Child Buffer failed"))
	(Tid_CreateImageHandleArrayFailed, _T("Create ImageHandle-Array failed"))
	(Tid_NoSourceImage, _T("Could not retrieve the source image."))
	(Tid_MilBarCodeInitFailed, _T("Mil Bar code initilized failed."))
	(Tid_BarCodeMatchStringLoadFailed, _T("Load of the match string for the Bar code result failed."))
	(Tid_UpdateOutputImageExtentsFailed, _T("Update Output image extents failed."))
	(Tid_InitExternalTaskFailed, _T("Initialized of External Taks failed."))
	(Tid_InitImageFailed, _T("Initialized of Image failed."))
	(Tid_UpdateTransformDataFailed, _T("Updating transform data failed."))
	(Tid_UpdateLineExtentDataFailed, _T("Updating Line extent data failed."))
	(Tid_UpdateLinearToolDataFailed, _T("Updating Linear tool data failed."))
	(Tid_UpdateBufferFailed, _T("Update buffer failed."))
	(Tid_UpdateTranslationFailed, _T("Update translation failed."))
	(Tid_InvalidModuleReadyPointer, _T("Invalid module ready pointer."))
	(Tid_InvalidRaidBitPointer, _T("Invalid raid bit pointer."))
	(Tid_IoController_RebuildOutpuListFailed, _T("IOController: Rebuild Output list failed."))
	(Tid_GetPixelDepthFailed, _T("Get Pixel Depth failed."))
	(Tid_GetImageExtentFailed, _T("Get Image Extent failed."))
	(Tid_SetImageExtentFailed, _T("Set Image Extent failed."))
	(Tid_GetEdgeAFailed, _T("Get Edge A failed."))
	(Tid_GetEdgeBFailed, _T("Get Edge B failed."))
	(Tid_Pattern_ResetImageFileFailed, _T("Pattern match: Reset image file failed."))
	(Tid_Pattern_SetCenterFailed, _T("Pattern match: Set Center failed."))
	(Tid_Pattern_GetModelImageNameFailed, _T("Pattern match: Get model image name failed."))
	(Tid_Pattern_SetSearchParamFailed, _T("Pattern match: Set search parameter failed."))
	(Tid_CreateLutFailed, _T("Create LUT failed."))
	(Tid_StatToolTestFailed, _T("Statistic Tool test failed."))
	(Tid_RebuildFailed, _T("Rebuild failed."))
	(Tid_InvalidOwner, _T("Invalid Owner."))
	(Tid_WrongType, _T("Wrong type."))
	(Tid_InvalidLinkedObjectOrSame, _T("Invalid Linked Object or itself."))
	(Tid_WrongInspection, _T("Object is not from the same Inspection."))
	(Tid_NoShapeHelper, _T("No shape helper found."))
	(Tid_NoCameraToMainImage, _T("No camera to main image found."))
	(Tid_NotImageTypePhysical, _T("The image type must be physical."))
	(Tid_NotCreated, _T("The Object is not created."))
	(Tid_ToolsetNotCreated, _T("The Toolset was not created."))
	(Tid_SetImageHandleIndexFailed, _T("SetImageHandleIndex failed."))
	(Tid_CopyImagesFailed, _T("Copy of images failed."))
	(Tid_RunFilterFailed, _T("Run filter failed."))
	(Tid_RunWarpFailed, _T("Run warp failed."))
	(Tid_RunRotateFailed, _T("Run Rotate failed."))
	(Tid_RunArithmeticFailed, _T("Run Arithmetic failed."))
	(Tid_LockingFailed, _T("Locking failed."))
	(Tid_ExternalTask_CheckToRunFailed, _T("External task: check if runable failed."))
	(Tid_ExternalTask_UnknownException, _T("External task: Unknown exception. %s"))
	(Tid_BinarizeFailed, _T("Binarize failed."))
	(Tid_SetValueFailed, _T("Setting of value failed."))
	(Tid_RunImagePolarFailed, _T("Prepare of run image polar transformation failed."))
	(Tid_UnknownException, _T("Unknown exception."))
	(Tid_EmptyValueList, _T("Empty value list."))
	(Tid_InvalidRange, _T("Invalid range"))
	(Tid_RunLinearEdgeFailed, _T("Runing of linear edge processing failed."))
	(Tid_RunLinearEdgeFailed, _T("Runing of linear edge processing failed."))
	(Tid_ProcessCommandQueueFailed, _T("ProcessCommandQueue failed."))
	(Tid_ArchiveTool_InitFlagFalse, _T("ArchiveTool-init Flag is false."))
	(Tid_RecalcLUTFailed, _T("Recalcuation of LUT failed."))
	(Tid_RunLutFailed, _T("Run Lut failed."))
	(Tid_StringTooLarge, _T("String too large."))
	(Tid_ErrorMcodeGetResult, _T("Function McodeGetResult return error: %s"))
	(Tid_StdException, _T("Std:Exception  what: %s"))
	(Tid_ColorToolExtentsChanged, _T("For backward compatibility: The ROI of at least one Color tool in the configuration has been changed to the size of the Main image"))
	(Tid_FailstatusNotFound, _T("Could not get Failstatus"))
	;
} //namespace SvStl