//*****************************************************************************
/// \copyright (c) $YEAR$,$YEAR$ by Körber Pharma Inspection GmbH. All Rights Reserved
/// All Rights Reserved 
//*****************************************************************************
/// Class to generate a text form a ID (enum) and additional text list depending of language settings
//******************************************************************************
#pragma once

#pragma region Includes
//Moved to precompiled header: #include <map>
//Moved to precompiled header: #include <tchar.h>
//Moved to precompiled header: #include <boost\assign\std\map.hpp>
//Moved to precompiled header: #include <boost\assign\list_of.hpp>

#include "MessageTextEnum.h"
#pragma endregion Includes

namespace SvStl
{
	typedef std::map<MessageTextEnum, std::string> MessageTextMap;

	MessageTextMap cMessageTextMap
	{
		{Tid_Empty, _T("")},
		{Tid_Default, _T("{0}")},
		{Tid_Started, _T("Started")},
		{Tid_Stopped, _T("Stopped")},
		{Tid_ReturnValue, _T("Return Value: {0}")}, 
		{Tid_ErrorClass, _T("Error Nbr = {0}, Program Cd = {1}")},
		{Tid_XmlParserError, _T("{0}, Error Code:{1}, On line {2} position {3}")},
		{Tid_RestoreVariantError, _T("RestoreVariant returns: {0}")},
		{Tid_TranslateVariantError, _T("TranslateVariant returns: {0}")},
		{Tid_ToVariant_InvalidArgument, _T("Invalid Argument in function ToVariant")},

		{Tid_XML_UnexpectedType, _T("Unexpected TreeElementType in OnStartElement")},
		{Tid_XML_UnexpectedOnElementData, _T("Unexpected OnElementData")},
		{Tid_XML_InvalidPointer, _T("Invalid Pointer")},
		{Tid_XML_InvalidArrayElement, _T("Invalid ArrayElement in OnEndElement")},
		{Tid_XML_Error, _T("Error in Line, Column, Errornumber: {0} , {1} , {2}: {3}")},

		//SVObserver SVDLLToolLoadLibraryClass
		{Tid_ToolLoadError_ImageDef, _T("Error in MIL/HBITMAP function definitions.")},
		{Tid_ToolLoadError_NoImageDef, _T("Neither MIL nor HBITMAP image functions are defined.")},
		{Tid_ToolLoadError_BothSetsImagesDef, _T("Both sets of MIL and HBITMAP image functions are defined.")},
		{Tid_ToolLoadError_BothImagesDef, _T("Both MIL and HBITMAP image functions are defined.")},
		{Tid_ToolLoadError_InFunctionDef, _T("Error in MIL/HBITMAP image functions definitions.")},
		{Tid_ToolLoadError_SimpleTest, _T("SimpleTest failed.")},
		{Tid_ToolLoadError_SimpleTestException, _T("SimpleTest failed - exception.")},
		{Tid_ToolLoadError_DllStartup, _T("DLL Startup function failed.")},
		{Tid_ToolLoadError_DllStartupException, _T("DLL Startup function failed.- exception")},
		{Tid_ToolLoadError_GetToolName, _T("DLL GetToolName function failed.")},
		{Tid_ToolLoadError_GetToolNameException, _T("DLL GetToolName failed.- exception")},
		{Tid_ToolLoadError_GetToolVersion, _T("DLL GetToolVersion function failed.")},
		{Tid_ToolLoadError_GetToolVersionException, _T("DLL GetToolVersion function failed - exception.")},
		{Tid_GetProcAddressError_SimpleTest, _T("GetProcAddress failed SimpleTest")},
		{Tid_GetProcAddressError_GetToolName, _T("GetProcAddress failed GetToolName")},
		{Tid_GetProcAddressError_GetToolVersion, _T("GetProcAddress failed GetToolVersion")},
		{Tid_GetProcAddressError_RunTool, _T("GetProcAddress failed RunTool")},
		{Tid_GetProcAddressError_Startup, _T("GetProcAddress failed Startup")},
		{Tid_GetProcAddressError_ShutDown, _T("GetProcAddress failed ShutDown")},
		{Tid_GetProcAddressError_InitializeRun, _T("GetProcAddress failed InitializeRun")},
		{Tid_GetProcAddressError_UninitializeRun, _T("GetProcAddress failed UninitializeRun")},
		{Tid_GetProcAddressError_GetInputValueDefinitions, _T("GetProcAddress failed GetInputValueDefinitions")},
		{Tid_GetProcAddressError_DestroyInputValueDefinitionStructures, _T("GetProcAddress failed DestroyInputValueDefinitionStructures")},
		{Tid_GetProcAddressError_DestroyResultValueDefinitionStructures, _T("GetProcAddress failed DestroyResultValueDefinitionStructures")},
		{Tid_GetProcAddressError_SetInputValues, _T("GetProcAddress failed SetInputValues")},
		{Tid_GetProcAddressError_GetResultValues, _T("GetProcAddress failed GetResultValues")},
		{Tid_GetProcAddressError_GetMessageString, _T("GetProcAddress failed GetMessageString")},
		{Tid_GetProcAddressError_ValidateValueParameter, _T("GetProcAddress failed ValidateValueParameter")},
		{Tid_GetProcAddressError_GetResultValueDefinitions, _T("GetProcAddress failed GetResultValueDefinitions")},
		{Tid_GetProcAddressError_GetNumberOfInputImages, _T("GetProcAddress failed GetNumberOfInputImages")},
		{Tid_GetProcAddressError_GetResultImageDefinitions, _T("GetProcAddress failed GetResultImageDefinitions")},
		{Tid_GetProcAddressError_DestroyImageDefinitionStructure, _T("GetProcAddress failed DestroyImageDefinitionStructure")},
		{Tid_ToolLoadError, _T("Could not load DLL (LoadLibrary failed).")},
		{Tid_RunTool_Exception, _T("SVRunTool: Exception {0} raised by '{1}'")},
		{Tid_SVInitializeRun_Exception, _T("SVInitializeRun: Exception {0} raised by '{1}'")},
		{Tid_CouldNotCopyDll, _T("Could not copy DLL because a different version is used by another tool")},

		//Defines for SVConfigurationObjects
		{Tid_CreateSFailed, _T("Create {0} failed")},
		{Tid_NumberOfIosMissing, _T("the Number of Ios Entries is missing.")},
		{Tid_IOEntryIsMissing, _T("an IO Entry is missing.")},
		{Tid_CreationOfPPQFailed, _T("The PPQ Object could not be created.")},
		{Tid_InputIsMissing, _T("an Input tag is missing")},
		{Tid_MsgIOTypeIsMissing, _T("an IO Type is missing")},
		{Tid_MsgIONameIsMissing, _T("an Item Name is missing")},
		{Tid_MsgPPQPOsitionIsMissing, _T("a PPQ Position is missing")},

		{Tid_CouldNotExecuteFormatString, _T("could not execute '{0}'")},

		//RangeValue
		{Tid_RangeValue_WrongRange, _T("{0} must between {1} and {2}.")},
		{Tid_Init_RangeControlFailed, _T("Initialisation of range control failed.")},
		{Tid_ErrorUnknownEnum, _T("Unknown enum")},
		{Tid_FailHigh, _T("Fail High")},
		{Tid_FailLow, _T("Fail Low")},
		{Tid_WarnHigh, _T("Warn High")},
		{Tid_WarnLow, _T("Warn Low")},
		{Tid_IsLessThan, _T("ERROR:\n{0}\nis less than\n{1}")},
		{Tid_IsInvalidRef, _T("ERROR:\n{0}: {1}\nis an invalid reference.")},

		{Tid_RingBuffer_Depth_Invalid_Value, _T("RingBuffer Depth has to be between {0} and {1}, current {2}")},
		{Tid_Error_NoFontFileSpec, _T("No Font File Specified")},
		{Tid_Error_FontFileNotExist, _T("Font File Does Not Exist: {0}")},
		{Tid_Error_FontFileEmpty, _T("Font File Empty: {0}")},
		{Tid_ArchiveTool_PathEmpty, _T("Archive Path is empty")},
		{Tid_ArchiveTool_CreateFileFailed, _T("Create Archive File \"{0}\" Failed")},
		{Tid_ArchiveTool_CreatePathFailed, _T("Create Archive Path \"{0}\" Failed")},
		{Tid_ArchiveTool_WriteToFileFailed, _T("Write to Archive File failed")},
		{Tid_ArchiveTool_AllocImageFailed, _T("Allocate Image Buffer failed: {0}")},
		{Tid_ArchiveTool_NotEnoughImageBuffer, _T("All Archive Tools combined need more image memory than is available.")},
		{Tid_OnlyOneArchiveImageWhenAlternativeImagePath, _T("Only one Archive Image allowed when Alternative Image Path is selected")},

		{Tid_BarCode_UnableToRead, _T("Bar Code Analyzer was unable to read\nthe match string from file. Check the\nanalyzer settings for proper match string.")},
		{Tid_BarCode_UnableToSave, _T("Bar Code Analyzer was unable to save\nthe match string to file. Check the\nanalyzer settings for proper match string.")},
		{Tid_BlobAnalyzer_ResultCreationFailed, _T("Creation of Blob Analyzer Result Failed")},
		{Tid_CreationFailed, _T("Creation of {0} Failed")},
		{Tid_CreationOf2Failed, _T("Creation of {0} \"{1}\" failed.")},
		{Tid_Command_StartSvimConfig, _T("Informational - Starting PutSVIMConfig")},
		{Tid_Command_EndSvimConfig, _T("Informational - Ending PutSVIMConfig")},
		{Tid_ErrorMIL, _T("{0} - An error has occurred, MIL error code = {1}, MIL error Text = {2}")},
		{Tid_ErrorGettingPPQ, _T("Error getting PPQ.")},
		{Tid_ErrorGettingInputObjectList, _T("Error getting input object list.")},
		{Tid_ErrorGettingPPQCount, _T("Error getting PPQ count.")},
		{Tid_Acquisition_SourceInformationFailed, _T("Failed to get acquisition source information!")},
		{Tid_TooManyVariables, _T("{0}\nToo many variables.")},
		{Tid_EquationParserError, _T("{0}\nSyntax Error at position {1}")},
		{Tid_InvalidData, _T("Invalid Data")},
		{Tid_Error_NoResultObject, _T("Cannot find the Result Object")},
		{Tid_ImageClass_DestroyError, _T("Failed to destroy the image object!")},
		{Tid_DisplayedImageIsUnavailable, _T("Displayed image is unavailable")},
		{Tid_ErrorNotAllDataItemsFound, _T("Not All Data List items found")},
		{Tid_ErrorNotAllImageItemsFound, _T("Not All Image List items found")},
		{Tid_ErrorProcessNotifyLastInspected, _T("ProcessNotifyWithLastInspected - {0}")},
		{Tid_RejectTRBeforeInterestDecision, _T("Reject TriggerRecord data for one inspection before final PPQ-decision is finished.")},
		{Tid_Unknown, _T("Unknown")},
		{Tid_ErrorRemovingAllInputRequests, _T("Error removing all input requests.")},
		{Tid_ErrorRemovingAllInputImageRequests, _T("Error removing all input image requests.")},
		{Tid_IPDoc_NoCameraColorAttached, _T("Color camera not attached to this IPDoc")},
		{Tid_ErrorGettingTimeStamp, _T("Error getting time stamp.")},
		{Tid_ErrorNotAllRejectConditionItemsFound, _T("Not All Reject Condition List items found")},
		{Tid_ReleaseProduct, _T("Release Product - {0}")},
		{Tid_ErrorCopyLastInspectedToReject, _T("Copy Last Inspected To Reject failed")},
		{Tid_SharedMemorySizeTooBig, _T("Required Shared Memory is bigger than maximum of DWORD")},
		{Tid_SVIODoc_ClosingImpossible, _T("Invalid Operation!\nThe IO Dialog can not be closed without\nclosing the whole configuration.")},
		{Tid_SVIPDoc_ClosingImpossible, _T("Invalid Operation!\nIf You wish to remove this inspection\nGo to the Edit menu and Select Edit Configuration.")},
		{Tid_SVIPDoc_GoIntoRegTestFailed, _T("Inspection is unable to go into Regression Test Mode. There is an unknown error with the inspection.")},
		{Tid_ErrorDetachingInput, _T("Error detaching input.")},
		{Tid_LightReference_NotAvailable, _T("Light Reference not available for {0}")},
		{Tid_LUT_NotAvailable, _T("LUT not available for camera(s)")},
		{Tid_LUT_ShouldOverwriteAllBands, _T("Selecting this option will overwrite all bands with the currently displayed LUT information. Continue?")},
		{Tid_Error_WrongCameraModel, _T("Wrong camera model: Expected {0}, Current {1}")},
		{Tid_Error_WrongCameraVendor, _T("Wrong camera vendor: Expected {0}, Current {1}")},
		{Tid_CreateBufferFailed, _T("Failed to create an image buffer!")},
		{Tid_CreateImageChildBuffer_parent, _T("\"{0}\" was located partially or completely outside of "
			"the bounds of \"{1}\".\nIt has been moved and/or resized "
			"to fit in the bounds.\nThis configuration should be "
			"saved to prevent this message from appearing again.")},
		{Tid_CreateImageChildBuffer_child, _T("\"{0}\" was located partially or completely outside of "
			"the bounds of its parent image.\nIt has been moved "
			"and/or resized to fit in the bounds.\nThis configuration "
			"should be saved to prevent this message from appearing "
			"again.")},
		{Tid_CreateImageChildBuffer, _T("A child buffer was located partially or completely outside "
			"of the bounds of its parent image.\nIt has been moved "
			"and/or resized to fit in the bounds.\nThis configuration "
			"should be saved to prevent this message from appearing "
			"again.")},
		{Tid_MatroxImage_UnableToFindFile, _T("Unable to locate image file:\n{0}\n\nBrowse...")},
		{Tid_UnknownFileFormat, _T("Unknown File Format!")},
		{Tid_FailedToLoadImage, _T("Failed to load an image!")},
		{Tid_FailedToSaveImage, _T("Unable to Save Image")},

		//Custom Filter 2
		{Tid_DataInvalidKernelSize, _T("The Kernel array size [{0}] does not match the size of the Kernel Width [{1}] and Height [{2}]")},
		{Tid_DataInvalidKernelWidth, _T("The Kernel Width is not valid [{0}], it must be odd and be between the limits including 1 and {1}")},
		{Tid_DataInvalidKernelHeight, _T("The Kernel Height is not valid [{0}], it must be odd and be between the limits including 1 and {1}")},
		{Tid_DataInvalidNormalizationFactor, _T("The Normalization Factor is not allowed to be 0 or negative")},
		{Tid_ExportFailed, _T("Custom filter export failed")},
		{Tid_ImportFailed, _T("The Custom Filter file [{0}] could not be imported.\n{1}")},
		{Tid_XmlFormatInvalid, _T("The XML format is invalid.")},
		{Tid_VersionMismatch, _T("Version mismatch.")},
		{Tid_ImportFailedDataInvalid, _T("Custom filter import failed, Kernel data is invalid.")},

		{Tid_True, _T("TRUE")},
		{Tid_False, _T("FALSE")},
		{Tid_ConditionalValidated, _T("Conditional Equation Validated Successfully\nCondition = {0}")},
		{Tid_FormulaValidated, _T("Formula Validated Successfully\n Value = {0}")},
		{Tid_ConditionalSelectedValidated, _T("Selected Text validated successfully\n Condition = {0}") },
		{Tid_FormulaSelectedValidated, _T("Selected Text validated successfully\n Value = {0}") },
		{Tid_Error_InvalidFormula, _T("An Invalid Formula has been detected.\nThe Formula must be valid to exit this dialog.")},
		{Tid_Error_CreationFilterFailed, _T("Creation of Filter Failed")},
		{Tid_Error_ToolPositionError, _T("Changing image source has placed the tool outside of the selected source image. Please either: "
			"select a new image source, resize the image source to contain this tool, or resize/position this tool to fit on the source image.")},
		{Tid_RingBuffer_Depth_Invalid_ValueString, _T("RingBuffer Depth has to be between {0} and {1}, current {2}")},
		{Tid_RingBuffer_ImageIndex_Invalid_ValueString, _T("RingBuffer Image Index {0} value invalid.")},
		{Tid_Error_NoDeviceContext, _T("No device context available!")},
		{Tid_Lpt_WrongState, _T("Select Line In wrong State")},
		{Tid_Sax_ConInitializeExFailed, _T("CoInitializeEx Failed")},
		{Tid_UnknowThread, _T("Unknown Thread")},
		{Tid_SeedImageDifferentSize, _T("Seed image and Source image are of different sizes but they must have the same size.")},
		{Tid_Value_Invalid, _T("Value has to be between {0} and {1}, current {2}")},
		{Tid_Error_ToolPositionError_Three_Button, _T("Changing image source has placed the tool outside of the selected source image. Please either: "
					"select a new image source, resize the image source to contain this tool, or resize/position this tool to fit on the source image. "
					"Press 'Yes' to enable auto fit." 
					"Press 'No' to resize the tool to the maximum size"
		)},

		//MatroxGigE
		{Tid_MatroxGigE_Connect_FindCameraError, _T("HandleConnect - FindCamera Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Connect_GetDigitizerError, _T("HandleConnect - GetDigitizer Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Connect_AllocError, _T("HandleConnect - AllocDigitizer Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Connect_ReadError, _T("HandleConnect - ReadCameraFormat Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Connect_CreateError, _T("HandleConnect - CreateAcquisitionBuffers Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Connect_ReloadError, _T("HandleConnect - Reload Camera Parameters Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Connect_StartDigitizerError, _T("HandleConnect - StartDigitizer Error - Device {0}")},
		{Tid_MatroxGigE_Disconnect_FindCameraError, _T("HandleDisconnect - FindCamera Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Disconnect_GetDigitizerError, _T("HandleDisconnect - GetDigitizer Error ({0}) - Device {1}")},
		{Tid_MatroxGigE_Disconnect, _T("CameraPresentCallback - Disconnect - Device {0}")},
		{Tid_MatroxGigE_Connect, _T("CameraPresentCallback - Connect - Device {0}")},

		{Tid_FileCamera_NoImageFile, _T("FileAcquisition::No Image File to Load, possible Invalid or Empty Directory {0}")},
		{Tid_FileCamera_LoadFailed, _T("FileAcquisition::Unable to Load Image File {0}")},
		{Tid_FileAcquisition_FormatError, _T("FileAcquisition::CopyImage - Error in Format")},
		{Tid_CameraEndFrame_GetNextBufferFailed, _T("CameraEndFrame({0}): GetNextBuffer failed")},
		{Tid_ObjectBuilder_SetObjectValueError, _T("SVObjectBuilder::SetObjectValue Error:\n Set Object Member Value failed!")},
		{Tid_ErrorUsedPreviouslyForSec, _T("This was previously used for .sec files.")},

		//ParseError
		{Tid_ParseError_NameMustNotContainKeyword, _T("Parser Error:\nName expression expected, valid names must not contain keywords!")},
		{Tid_ParseError_OutOfMemory, _T("Parser Error:\nOut of memory!")},
		{Tid_ParseError_NameExpressionExpected, _T("Parser Error:\nName expression expected!")},
		{Tid_ParseError_OwnerNotExist, _T("Parser Error:\nOwner doesn't exist, cannot access member!")},
		{Tid_ParseError_UnexpectedMember, _T("Parser Error:\nUnexpected member access operator!")},
		{Tid_ParseError_ExpressionExpected, _T("Parser Error:\nExpression expected!")},
		{Tid_ParseError_UnknownExpression, _T("Parser Error:\nUnknown expression!")},
		{Tid_ParseError_UnexpectedEndOfCommand, _T("Parser Error:\nUnexpected end of command!")},
		{Tid_ParseError_CriticalErrorRemovingDependencies, _T("Critical Error removing external dependencies")},
		{Tid_ParseError_UnexpectedEndOfParse, _T("ParserState: READ_STRING\nParser Error, unexpected end of parse string while reading string...")},
		{Tid_ParseError_UnexpectedEndOfName, _T("ParserState: READ_NAME_STRING\nParser Error, unexpected end of name string while parsing ...")},
		{Tid_ParseError_EmptyToken, _T("ParserState: READ_GUID_STRING\nParser Error, empty token found...")},
		{Tid_ParseError_NameOperandExpected, _T("Parser Error:\nName operand expected!")},
		{Tid_ParseError_OperatorExpected, _T("Parser Error:\nOperator, expected!")},
		{Tid_ParseError_OperandExpected, _T("Parser Error:\nObject operand, class operand or embedded operand expected!")},
		{Tid_ParseError_CommandTerminationExpected, _T("Parser Error:\nCommand termination expected!")},
		{Tid_ParseError_TooManyExpressions, _T("Parser Error:\nToo many expressions found!")},
		{Tid_ParseError_ClassOperandExpected, _T("Parser Error:\nClass operand expected!")},
		{Tid_ParseError_OperatorOperand, _T("Parser Error:\nOperator operand expected!")},
		{Tid_ParseError_ObjectOperandExpected, _T("Parser Error:\nObject operand expected!")},
		{Tid_ParseError_UnableToReadInputList, _T("Parser Error:\nUnable to read input list!")},
		{Tid_ParseError_CommandTerminationOrObjectMemberExpected, _T("Parser Error:\nCommand termination or object member definition expected!")},
		{Tid_ParseError_NoValidObjectOwner, _T("Parser Error:\nNo valid object owner given!")},
		{Tid_ParseError_WrongEmbeddedValues, _T("Parser Error:\nWrong embedded values!")},
		{Tid_ParseError_CannotConstructObject, _T("Parser Error:\nCannot construct new object!")},
		{Tid_ParseError_ObjectRequired, _T("Parser Error:\nObject required for Member!")},
		{Tid_ParseError_ValuesExpected, _T("Parser Error:\nValues expected!")},
		{Tid_ParseError_NoValidObject, _T("Parser Error:\nNo valid object given!")},
		{Tid_ParseError_SetObjectMemberFailed, _T("Parser Error:\nSet Object Member Value failed!")},
		{Tid_Error_ScriptParseFailed, _T("{0} parse was not successful")},

		//SVObserver
		{Tid_Error_ConfigWarnFileError, _T("Loading of the configuration warning file ({0}) failed. Either the file is missing or it has a syntax error.") },
		{Tid_Error_ConfigWarnSyntaxError, _T("Loading of the configuration warning file failed. It has a syntax error.") },
		{Tid_SVObserver_CannotRun_WrongModelNumber, _T("Configuration cannot enter Run. The current configuration hardware does not match system hardware. "
			"The system's Model Number is ( Model # {0} {1} {2} {3} ). Please verify that the shown model number is correct and contact your system administrator.")},
		{Tid_SVObserver_InitializationFailure, _T("Initialization failure (Model Number {0}):\n{1}")},
		{Tid_SVObserver_ModelNumberInvalid, _T("The model number specified in OEMINFO.INI is invalid.")},
		{Tid_SVObserver_AuthorizationFailed_Modification, _T("Authorization Failed.\n\nUtility Modification requires 'User Manager' privilege.")},
		{Tid_SVObserver_AuthorizationFailed_Execution, _T("Authorization Failed.\n\nUtility Execution requires 'User Manager' privilege.")},
		{Tid_SVObserver_MatroxGigELicenseNotFound, _T("Matrox GigE License not found")},
		{Tid_SVObserver_MatroxLicenseNotFound, _T("Matrox License not found")},
		{Tid_SVObserver_WrongVersionNumber, _T("This configuration was created by SVObserver {0}.\nYou are currently running SVObserver {1}.\n"
			"This configuration version may be incompatible with\nthe version of SVObserver that you are running.\nAre you sure you wish to continue ?")},
		{Tid_SVObserver_ConfigurationLoadFailed, _T("The configuration could not successfully load.\nhr = {0}.\n")},
		{Tid_SVObserver_SecurityFileLoadFailed, _T("Security File Failed to Load\n Using Default Security")},
		{Tid_SVObserver_WrongPathnameEntered, _T("Invalid path or file name found\n\nCheck your inputs and try it again!")},
		{Tid_SVObserver_RegisterClassObjectsFailed, _T("(hr=0x{0}), Unable to register class objects. COM interface ISVCommand unavailable.")},
		{Tid_SVObserver_RegisterClassObjectsFailed_Question, _T("(hr=0x{0}), Unable to register class objects. COM interface ISVCommand unavailable.\nDo you want to exit?")},
		{Tid_SVObserver_OleInitFailed, _T("OLE initialization failed.  Make sure that the OLE libraries are the correct version.")},
		{Tid_CanGoOnlineFailure_Trigger, _T("Configuration cannot enter Run.  There is an "
				"unknown error with Trigger {0} when the system attempted to enter Run.")},
		{Tid_CanGoOnlineFailure_Acquisition, _T("Configuration cannot enter Run.  Cannot connect to camera {0} when the system attempted to enter Run.")},
		{Tid_CanGoOnlineFailure_InspectionTool, _T("Configuration cannot enter Run.\n Error with \"{0}\" : {1}")},
		{Tid_CanGoOnlineFailure_Inspection, _T("Configuration cannot enter Run.  There is an "
								"unknown error with an inspection {0} when the system attempted to enter Run.")},
		{Tid_CanGoOnlineFailure_ConditionalOutput, _T("Configuration cannot enter Run.  There is an "
								"unknown error by resolving the coditionalOutputs when the system attempted to enter Run.")},
		{Tid_GoOnlineFailure_RecycleProduct, _T("Configuration cannot enter Run.  There is an "
							"unknown error with a PPQ when it attempted to recycle a product when the system was going online.")},
		{Tid_GoOnlineFailure_RecycleProductId, _T("Configuration cannot enter Run.  There is the "
							"error {0} with a PPQ when it attempted to recycle a product when the system was going online.")},
		{Tid_GoOnlineFailure_Inspection, _T("Configuration cannot enter Run.  There is an "
							"unknown error with Inspection {0} when the system was going online.")},
		{Tid_GoOnlineFailure_Acquisition, _T("Configuration cannot enter Run.  Cannot reach camera {0} when the system was going online.")},
		{Tid_GoOnlineFailure_Trigger, _T("Configuration cannot enter Run.  There is an "
							"unknown error with Trigger {0} when the system was going online.")},
		{Tid_GoOnlineFailure_InternalTrigger, _T("Configuration cannot enter Run.  There is the "
							"error {0} with enable internal Trigger when the system was going online.")},
		{Tid_GoOnlineFailure_CreatePPQThread, _T("Configuration cannot enter Run.  There is the "
							"error {0} by creating the PPQ Thread.")},
		{Tid_GoOnlineFailure_InvalidPointerConfig, _T("Configuration cannot enter Run.  Invalid pointer of configuration or mainWnd.")},
		{Tid_GoOnlineFailure_ModuleReadyOutput, _T("Configuration cannot enter Run.  Cannot write to module ready output.")},
		{Tid_ErrorNotEnoughDiskSpace, _T("Unable to set monitor list for {0} - Not enough Disk Space Available")},
		{Tid_GoOnlineFailure_SendCameraParam, _T("Configuration cannot enter Run.  There is an "
							"unknown error by sending camera parameter when the system was going online.")},
		{Tid_AmountOfSystemMemoryText, _T("Amount of physical memory = {0}")},
		{Tid_Version, _T("\nVersion {0}")},
		{Tid_ConfigLoadTime, _T("{0}\nload time {1} ms")},
		{Tid_UserQuestionCloseConfig, _T("Are you sure you want to close the current SVObserver application {0}?\n\nALL CURRENT RUNNING INSPECTIONS WILL BE STOPPED!")},
		{Tid_UserQuestionSaveChanges, _T("Save changes to {0}?")},
		{Tid_UnableConfig, _T("Unable to {0} configuration {1} !")},
		{Tid_Load, _T("load")},
		{Tid_Save, _T("save")},
		{Tid_GoOnlineTime, _T("{0}\nGoOnline time {1} ms")},
		{Tid_FunctionNotImplemented, _T("Implementation of function '{0}' for {1} is missing")},

		{Tid_Camera_UseQuestion, _T("Would you like to use this camera file for all camera choices?")},
		{Tid_Config_SwitchIOQuestion, _T("By switching the system (product) the input and outputs need to be reset, do you wish to continue?")},
		{Tid_Config_InspectionImportFailed, _T("Inspection Import failed. Error = {0}")},
		{Tid_Config_CameraFileNameInvalid, _T("Camera file name is invalid {0}")},
		{Tid_Config_CameraFileInvalid, _T("Camera file is invalid {0}")},
		{Tid_Error_NoMilHostBuffer, _T("No Mil Host Buffer Pointer")},
		{Tid_Error_MilDestroy, _T("Mil destroy error")},
		{Tid_Error_MilImageTypeInvalid, _T("MIL Image Type Not 8 Bit Unsigned: {0}")},
		{Tid_Error_FontNotMfoExt, _T("Font File Requires '.mfo' Extension: {0}")},
		{Tid_Error_NoFontConstraintsFileSpec, _T("No Font Constraints File Specified")},
		{Tid_Error_FontConstraintsRequiredMfoExt, _T("Font Constraints File Requires '.mfo' Extension: {0}")},
		{Tid_Error_FontConstraintsFileNotExist, _T("Font Constraints File Does Not Exist: {0}")},
		{Tid_Error_FontConstraintsFileEmpty, _T("Font Constraints File Empty: {0}")},
		{Tid_Error_NoFontControlsFileSpec, _T("No Font Controls File Specified")},
		{Tid_Error_FontControlsRequiredMfoExt, _T("Font Controls File Requires '.mfo' Extension: {0}")},
		{Tid_Error_FontControlsFileNotExist, _T("Font Controls File Does Not Exist: {0}")},
		{Tid_Error_FontControlsFileEmpty, _T("Font Controls File Empty: {0}")},
		{Tid_ImportInspectionError, _T("Inspection was exported using SVObserver {0}. \tThis is incompatible with SVObserver {1}.")},
		{Tid_Error_InvalidThresholdValue, _T("Invalid Threshold Value")},
		{Tid_Pattern_Model2Large, _T("Model is larger than the ROI of the Window Tool.")},
		{Tid_Pattern_DontCare2Small, _T("The don't care image is to small. It must have at least the size of the model.")},
		{Tid_Pattern_Invalid_ShouldLeave, _T("Pattern Model is invalid. Do you want to change Model (Yes) or leave dialog (No)?")},
		{Tid_ErrorGettingInputs, _T("Error getting inputs.")},
		{Tid_ErrorFindingPPQEntries, _T("Error finding PPQ entries.")},
		{Tid_InvalidReference, _T("%s: Invalid reference")},

		{Tid_InvalidImageFileType, _T("Invalid image file type.")},
		{Tid_RegressionTest_WrongListSize, _T("Selection Error: Lists must be the same size.  Please select again.")},
		{Tid_RegressionTest_NoFileSelected, _T("Selection Error in {0}: \"Use single file\" is selected for one of the cameras but a file was not selected. Select again?")},
		{Tid_RegressionTest_WrongFormat, _T("Selection Error in {0}: \"Use list of files\" selected, but the file name does not match\n the acceptable format (<file name>_<sequence number>.bmp). Select again?")},
		{Tid_RegressionTest_NoFilesSelected, _T("Selection Error: \"No files\" selected.  Select again?")},
		{Tid_RegressionTest_FileNotExist, _T("Selection Error in {0}: File does not exist.  Select again?")},
		{Tid_RegressionTest_EmptyDirectory, _T("Selection Error in {0}: Directory has no image files.  Select again?")},
		{Tid_RemoteOutput_TriggerCountDeleteError, _T("Trigger Count Cannot Be deleted")},
		{Tid_RemoteOutput_DeletingOutput, _T("Are you sure you want to delete this Output?")},
		{Tid_RemoteOutput_DeletingAllOutput, _T("Are you sure you want to delete All Entries for {0}")},
		{Tid_ResultView_InitFailed, _T("Failed to init inspection result view!")},
		{Tid_StatTool_ResultFailed, _T("Creation of Statistics Result Failed")},

		{Tid_ArchiveQueueFull, _T("Archive Queue is full, file {0} is skipped.")},
		{Tid_ArchiveImageNotFound, _T("Image to Archive is not valid or found.")},
		{Tid_InvalidPath, _T("Invalid Path '{0}'!") },
		{Tid_InvalidKeywordsInPath, _T("Invalid keywords in path '{0}'!") },

		{Tid_FileName_Exists, _T("{0} already exists.\nDo you want to replace it?")},
		{Tid_MaxImagesForArchiveToolTooHigh, _T("{0} max. images for Archive Tool selected: Must be less than {1} !")},
		{Tid_NotEnoughArchiveImageMemory, _T("Not enough available Archive Image Memory.")},
		{Tid_NotEnoughArchiveImageMemoryPleaseDeselect, _T("Not enough available Archive Image Memory.\nPlease deselect some images, decrease 'Max. Images' or 'Max. Queue' or change 'When to archive' mode.")},
		{Tid_Threshold_OutOfRange, _T("Out of Range!\n(0 ... 255)")},
		{Tid_CriticalUnableToConnectTo, _T("Unable to connect to {0}")},
		{Tid_Error_DuplicateEmbeddedId, _T("Error - Duplicate Embedded ID found")},
		{Tid_Error_CannotAddInputRequest, _T("Cannot Add Input Request.\nPlease contact technical support specialist.")},
		{Tid_Error_CannotAddInputRequestMarker, _T("Cannot Add Input Request Marker.\nPlease contact technical support specialist.")},
		{Tid_Error_CannotRunOnce, _T("Cannot Run Once.")},
		{Tid_ErrorIn, _T("Error in {0}")},
		{Tid_Error_NoAnalyzerDetails, _T("No Analyzer Details available!\nTry to select an Analyzer first.\nNOTICE: Some Tools don´t have an Analyzer!")},
		{Tid_Error_AnalyzerCreationFailed, _T("Creation of Analyzer Failed")},
		{Tid_Error_AnalyzerInstantiationFailed, _T("Instantiation of Analyzer Failed")},
		{Tid_LinearSpecial_OrientationVertical, _T("Tool profile orientation is at vertical.  By turning rotation on the profile orientation will be set to horizontal. Do you wish to continue")},
		{Tid_LinearSpecial_IsRotated, _T("Tool is currently rotated.  By turning off rotation the figure will be drawn at a rotation angle of 0. Do you wish to continue")},
		{Tid_MaskPage_StartOCXFailed, _T("Static Mask Editor OCX Failed to Start")},
		{Tid_Error_CannotOpenFile, _T("Cannot open file {0} !")},
		{Tid_Error_CannotOpenTADlg, _T("Unable to open Tool Adjustment Dialog!")},
		{Tid_UnableStart_Utility, _T("Unable to start {0}\n({1}).\n\nCheck Utility Properties.")},
		{Tid_SetClipboardDataFailed, _T("Setting the data into the clipboard failed.")},
		{Tid_ClipboardDataConversionFailed, _T("The clipboard data conversion failed.")},
		{Tid_ClipboardMemoryFailed, _T("Clipboard memory allocation failed.")},
		{Tid_GetClipboardDataFailed, _T("Failed to retrieve the clipboard data.")},
		{Tid_ClipboardZipFailed, _T("Failed to zip clipboard data.")},
		{Tid_ClipboardUnzipFailed, _T("Failed to unzip clipboard data.")},
		{Tid_ClipboardInvalid, _T("Clipboard data is invalid")},
		{Tid_ToolInvalid, _T("The tool is invalid.")},
		{Tid_Clipboard_VersionMismatch, _T("The current SVObserver Version does not match the version coming from the clipboard.")},
		{Tid_ColorToolInsertFailed, _T("A color tool cannot be inserted into a non-color system.")},
		{Tid_MonoToolInsertFailed, _T("A tool which requires a mono source cannot be inserted in this position as no mono source is available.") },
		{Tid_LoopToolInsertLoopToolFailed, _T("Too many nesting levels ({0}) of tools. Only {1} allowed.")},
		{Tid_LoopTool, _T("loop tool")},
		{Tid_GroupTool, _T("group tool") },
		{Tid_RenameError_DuplicateName, _T("A duplicate name was found for the item being renamed\n{0}")},
		{Tid_ErrorInReset, _T("While resetting, an error occurred.")},
		{Tid_InValidNewExtents, _T("The new extents for the {0} are not valid")},
		{Tid_MilVersion_Error, _T("This version of SVObserver will not run with the installed MIL library. SVObserver needs MIL {0}. The installed version is {1}")},
		{Tid_StatToolInvalidVariable, _T("{0}\nError - The Selected Variable To Monitor does not exist.")},
		{Tid_PatModelSizeErr, _T("Invalid Model Size")},
		{Tid_PatInvalidFilename, _T("Not a Valid Model file")},
		{Tid_DontCareInvalidFilename, _T("Not a Valid Don't Care file")},
		{Tid_DontCareImage_LoadFailed, _T("Load of don't care image failed.")},
		{Tid_PatAllocModelFailed, _T("Pattern Model Allocation Failed.")},
		{Tid_PatAllocFailed, _T("Pattern image Allocation Failed.")},
		{Tid_PatAdditionalCandidatesErr, _T("Invalid Additional Candidates Value (range is 1 to 100)")},
		{Tid_PatCandidateSpaceErr, _T("Invalid Candidate Spacing Min Value (range is 1.0 to 100.0)")},
		{Tid_PatPreliminaryAcceptanceThresholdErr, _T("Invalid Preliminary Acceptance Threshold Value (range is 1.0 to 100.0)")},
		{Tid_Security_GainedAccess, _T("{0} - Gained Access")},
		{Tid_Security_Login, _T("Login")},
		{Tid_Security_Access, _T("Access - {0}")},
		{Tid_Security_UserNoRights, _T("User Does Not Have Rights to This Function")},
		{Tid_Security_Access_Granted, _T(" User: {0}\n Gained Access to - {1}")},
		{Tid_Security_Access_Denied, _T(" User: {0}\n Attempt to Access - {1}")},
		{Tid_Security_Disabled, _T("Security Disabled")},
		{Tid_OS_Error_Message, _T("OS Error Number: {0} [{1}]\nMessage: {2}")},
		{Tid_ConvertTextToVariantFailed, _T("Convert text \"{0}\" to variant failed.")},

		{Tid_Drive_Full, _T(" {0} - drive is full.")},
		{Tid_ConditionalValue_Invalid, _T("The conditional value of tool \"{0}\" is invalid.")},

		{Tid_TableColumnName_NotUnique, _T("The name \"{0}\" is used already by another column.\nThe name must be unique.")},
		{Tid_TableColumnName_Empty, _T("The column name must not be empty and is not allowed to contain only invalid characters.")},
		{Tid_TableColumn_AddingFailed, _T("Adding a column failed. Error number {0}.")},
		{Tid_TableColumn_MovingFailed, _T("Moving a column failed. Error number {0}.")},
		{Tid_TableColumn_RemovingFailed, _T("Removing a column failed. Error number {0}.")},
		{Tid_TableColumn_RenamingFailed, _T("Renaming a column failed. Error number {0}.")},
		{Tid_TableColumn_TooManyEquation, _T("Too many equation for columns. Max number = {0}. Delete the last one.")},
		{Tid_TableObject_CreateFailed, _T("Creating the table object in the table tool failed.")},
		{Tid_TableObject_Nullptr, _T("Table object in the table tool is a nullptr.")},
		{Tid_TableObject_columnValueMapInvalid, _T("The columnValueMap in the table object has invalid entries.")},
		{Tid_TableObject_columnValue_NoFreeID, _T("Too many column equation, no free ID for the column value objects.")},
		{Tid_TableObject_createColumnValueObjectFailed, _T("Creating a value object in the table object failed.")},
		{Tid_TableObject_MaxRowWrongValue, _T("Maximum rows must be between {0} and {1}, current = {2}.")},
		{Tid_TableCopy_Nullptr, _T("No Source Table object is selected.")},
		{Tid_UnknownCommitError, _T("Unknown Commit or Reset error {0}.")},
		{Tid_UnknownCommandError, _T("Unknown Command error {0}.")},

		{Tid_MoreThanPercentUsed, _T("\nMore than %s% [%s%] has been used.")},
		{Tid_ConnectTableSourceFailed, _T("Connect Table Source \"{0}\" with \"{1}\" failed.")},
		{Tid_ConnectFailed, _T("Connect \"{0}\" failed.")},
		{Tid_ConnectInputFailed, _T("Connect Input failed.")},
		{Tid_ConnectInputFailedLinkedValueNotFound, _T("Connect Input failed: Linked Value ({0}) cannot be found") },
		{Tid_NoValidTableConnected, _T("There is no valid table connected to the tool.")},
		{Tid_Error_CreationAnalyzerFailed, _T("Creation of Analyzer Failed")},
		{Tid_Error_SetTableAnalyzerData, _T("Set from Table Analyzer Data failed: {0}")},
		{Tid_NoValidColumnConnected, _T("There is no valid column to the analyzer connected.")},
		{Tid_ExcludeHighMustBeHigher, _T("Exclude High must be higher than Exclude Low.")},
		{Tid_LinkedValue_ValidateStringFailed, _T("Set of parameter \"{0}\" failed: Invalid object name or value type.")},
		{Tid_ValueObject_ValidateStringFailed, _T("Set value \"{0}\" to parameter \"{1}\" failed: Invalid string.")},
		{Tid_SetEmbeddedValueFailed, _T("Setting of an embedded parameter failed: [{0}]")},
		{Tid_ValidateValue_InvalidElementInVariantArray, _T("Validate Value failed: Invalid element in VariantArray: {0}")},
		{Tid_ValidateValue_ArraySizeInvalid, _T("Validate Value failed: Array Size must be greater than zero.")},
		{Tid_ValidateValue_LinkedTypeInvalid, _T("Validate Value failed: Linked Type is invalid.") },
		{Tid_ValidateValue_LinkedObjectInvalid, _T("Validate Value failed: The Linked Object is invalid.") },
		{Tid_ValidateValue_FormulaFailed, _T("Validate Value failed: Formula is invalid.")},
		{Tid_UnexpectedError, _T("An unexpected error ocurred.")},
		{Tid_Too_Many_Blobs, _T("Too many blobs found, analyzer failed.")},
		{Tid_SetFeatureParameterFailed, _T("Feature parameter are invalid.")},
		{Tid_RemoveGrayFeature, _T("Remove gray features, because gray image is not set.")},
		{Tid_ExcludeBlobUpperBoundLowerThanLowerBound, _T("Upper Bound is lower than Lower Bound for feature {0}.")},
		{Tid_FeatureNameFailed, _T("Rename failed: Feature name must be unique and is not a name of a standard feature.")},
		{Tid_RangeBlobUpperBoundLowerThanLowerBound, _T("Range setting failed for feature {0}: {1}\nis less than\n{2}") },
		{Tid_InvalidDrawTypeWithSelectedFeatures, _T("Draw Step \"{0}\" is invalid, because the DrawType is not possible with the correct selected Features.")},
		{Tid_InvalidDrawTypeAfterDeletingFeature, _T("After deleting of a feature, the additional draw step \"{0}\" become invalid.")},

		{Tid_FailedtoStart, _T("Failed to start {0}")},
		{Tid_SocketInvalid, _T("Invalid socket Error: {0}")},
		{Tid_InvalidCommand, _T("Invalid Command received: {0}")},
		{Tid_CannotOpenReader, _T("Cannot open Reader")},
		{Tid_InvalidArguments, _T("Invalid arguments: {0}")},
		{Tid_InvalidMonitorlist, _T("Invalid monitor list name: {0}")},
		{Tid_RejectNotFound, _T("Reject not found")},
		{Tid_ProductNotFound, _T("Product not found")},
		{Tid_CreateChildBufferFailed, _T("Create Child Buffer failed")},
		{Tid_CreateImageHandleArrayFailed, _T("Create ImageHandle-Array failed")},
		{Tid_NoSourceImage, _T("Could not retrieve the source image.")},
		{Tid_MilBarCodeInitFailed, _T("Mil Bar code initilized failed.")},
		{Tid_MilBarCodeUnknowType, _T("Mil Bar code type unknown.")},
		{Tid_MilBarCodeECCNotFit, _T("ECC type does not correspond to the MIL bar code type.") },
		{Tid_MilBarCodeENCNotFit, _T("ENC type does not correspond to the MIL bar code type.") },
		{Tid_BarCodeMatchStringLoadFailed, _T("Load of the match string for the Bar code result failed.")},
		{Tid_UpdateOutputImageExtentsFailed, _T("Update Output image extents failed.")},
		{Tid_InitExternalTaskFailed, _T("External Task initialization failed.") },
		{Tid_InitImageFailed, _T("Image initialization failed.")},
		{Tid_UpdateTransformDataFailed, _T("Updating transform data failed.")},
		{Tid_UpdateLineExtentDataFailed, _T("Updating Line extent data failed.")},
		{Tid_UpdateLinearToolDataFailed, _T("Updating Linear tool data failed.")},
		{Tid_UpdateBufferFailed, _T("Update buffer failed.")},
		{Tid_UpdateTranslationFailed, _T("Update translation failed.")},
		{Tid_InvalidModuleReadyPointer, _T("Invalid module ready pointer.")},
		{Tid_GetPixelDepthFailed, _T("Get Pixel Depth failed.")},
		{Tid_GetImageExtentFailed, _T("Get Image Extent failed.")},
		{Tid_SetImageExtentFailed, _T("Set Image Extent failed.")},
		{Tid_GetEdgeAFailed, _T("Get Edge A failed.")},
		{Tid_GetEdgeBFailed, _T("Get Edge B failed.")},
		{Tid_Pattern_ResetImageFileFailed, _T("Pattern match: Reset image file failed.")},
		{Tid_Pattern_SetCenterFailed, _T("Pattern match: Set Center failed.")},
		{Tid_Pattern_GetModelImageNameFailed, _T("Pattern match: Get model image name failed.")},
		{Tid_Pattern_SetSearchParamFailed, _T("Pattern match: Set search parameter failed.")},
		{Tid_CreateLutFailed, _T("Create LUT failed.")},
		{Tid_StatToolTestFailed, _T("Statistic Tool test failed.")},
		{Tid_RebuildFailed, _T("Rebuild failed.")},
		{Tid_UpdateFromParentInformationFailed, _T("Update From Parent-Information failed.")},
		{Tid_UpdateTRCBuffersFailed, _T("Update TRC-Buffers failed.")},
		{Tid_InvalidOwner, _T("Invalid Owner.")},
		{Tid_WrongType, _T("Wrong type.")},
		{Tid_WrongValueType, _T("Wrong value type: Required Type is {0}.")},
		{Tid_InvalidOrRecursiveLinkedObject, _T("Invalid or recursive linked object.")},
		{Tid_WrongInspection, _T("Object is not from the same Inspection.")},
		{Tid_Invalid_Inspection, _T("Invalid Inspection.")},
		{Tid_NoShapeHelper, _T("No shape helper found.")},
		{Tid_NoCameraToMainImage, _T("No camera to main image found.")},
		{Tid_NotImageTypePhysical, _T("The image type must be physical.")},
		{Tid_NotCreated, _T("The Object is not created.")},
		{Tid_ToolsetNotCreated, _T("The Toolset was not created.")},
		{Tid_GetImageBufferToWriteFailed, _T("getImageToWrite failed.")},
		{Tid_CopyImagesFailed, _T("Copy of images failed.")},
		{Tid_RunFilterFailed, _T("Run filter failed.")},
		{Tid_RunWarpFailed, _T("Run warp failed.")},
		{Tid_RunRotateFailed, _T("Run Rotate failed.")},
		{Tid_RunArithmeticFailed, _T("Run Arithmetic failed.")},
		{Tid_LockingFailed, _T("Locking failed.")},
		{Tid_ExternalTask_CannotRun, _T("External task cannot run.")},
		{Tid_ExternalTask_UnknownException, _T("External task: Unknown exception.") },
		{Tid_ExternalDllSomethingWrongWithInputValue, _T("Something is wrong with the input value")},
		{Tid_ExternalDllErrorWhenTransferringResultValues, _T("Error when transferring result values")},
		{Tid_ExternalDllEditModeFreezeSetNoDllLoad, _T("While 'Edit Mode Freeze' is set, the external DLL cannot be changed!")},
		{Tid_ExternalDllError, _T("External DLL Error ({0})") },
		{Tid_ExternalDllPassesTheTest, _T("External DLL passes the test{0}.") },
		{Tid_ExternalDllProblemsOccurred, _T(" (but problems occurred)") },
		{Tid_BinarizeFailed, _T("Binarize failed.")},
		{Tid_SetValueFailed, _T("Setting of value failed.")},
		{Tid_RunImagePolarFailed, _T("Prepare of run image polar transformation failed.")},
		{Tid_UnknownException, _T("Unknown exception.")},
		{Tid_EmptyValueList, _T("Empty value list.")},
		{Tid_RunLinearEdgeFailed, _T("Running of linear edge processing failed.")},
		{Tid_ProcessCommandQueueFailed, _T("ProcessCommandQueue failed.")},
		{Tid_ArchiveTool_InitFlagFalse, _T("ArchiveTool-init Flag is false.")},
		{Tid_RecalcLUTFailed, _T("Recalcuation of LUT failed.")},
		{Tid_RunLutFailed, _T("Run Lut failed.")},
		{Tid_StringTooLarge, _T("String too large.")},
		{Tid_ErrorMcodeGetResult, _T("Function McodeGetResult return error: {0}")},
		{Tid_StdException, _T("Std:Exception what: {0}")},
		{Tid_ColorToolExtentsChanged, _T("For backward compatibility: The ROI of at least one color tool in the configuration has been changed to the size of the Main image")},
		{Tid_FailstatusNotFound, _T("Could not get Failstatus")},
		{Tid_WrongInputImageType, _T("The input image is the wrong color type")},
		{Tid_WriteCSVFileFailed, _T("Write to file {0} failed.")},
		{Tid_Error_SetServiceStatus, _T("SetServiceStatus returned error")},
		{Tid_Error_RegisterServiceHandler, _T("RegisterServiceCtrlHandler returned error")},
		{Tid_Error_CreateEvent, _T("Could not create the Event Handler")},
		{Tid_ZipFileFailed, _T("Failed to create {0} zip file.")},
		{Tid_UnzipFileFailed, _T("Failed to unzip {0} file.")},
		{Tid_SizeOfChildROIInvalid, _T("Invalid size of child ROI") },
		{Tid_GetImageFailed_NoTR, _T("Get image failed, because there is no trigger record")},
		{Tid_SM_SlotNotFound, _T("Shared memory slot with the MonitorList name: {0} not found")},

		{Tid_TRC_Error_ResetLocker, _T("Error with reference count in TriggerRecordController::ResetLocker")},
		{Tid_TRC_Error_ImageRefCount, _T("Error with reference count in ImageController")},
		{Tid_TRC_Error_SetImage_InvalidType, _T("Set image failed: Invalid image type.")},
		{Tid_TRC_Error_SetImage_TypeNotFit, _T("Set image failed: Buffer type don't fit to image.")},
		{Tid_TRC_Error_SetImage_InvalidPos, _T("Set image failed: Invalid image position.")},
		{Tid_TRC_Error_SetImages_SourceTROutOfData, _T("Set images failed: Source trigger record is Out-Of-Data.")},
		{Tid_TRC_Error_NoBufferFree, _T("New image buffer for struct {0} failed: No buffer free.")},
		{Tid_TRC_Error_UnknownStructID, _T("New image buffer failed : Unknown structID {0}.")},
		{Tid_TRC_Error_NewBufferFailed, _T("New image buffer for pos {0} failed.")},
		{Tid_TRC_Error_ResetBuffer_TooMany, _T("Reset Image Buffers failed: Too many buffers required ({0}). Maximum number is {1}.")},
		{Tid_TRC_Error_ResetBuffer_TooMuch, _T("Reset Image Buffers failed: Too much memory required (> {0} MB). Maximum size is {1} MB.")},
		{Tid_TRC_Error_CreateBuffer, _T("Create Buffer failed ({0}): Maybe too many buffers required.")},
		{Tid_TRC_Error_ResetAllReadyStarted, _T("Reset of TriggerRecord-structure already started with {0}. Restart with {1} not possible.")},
		{Tid_TRC_Error_ResetLocked, _T("Reset not possible, because it is locked.")},
		{Tid_TRC_Error_ResetWrongInspectionId, _T("Reset not possible, {0} is invalid inspectionId, number of inspection is {1}")},
		{Tid_TRC_Error_GlobalInitNotStarted, _T("Global init not started.")},
		{Tid_TRC_Error_TriggerRecordSize2Big, _T("TriggerRecordSize of {0} is too big. Maximal {1} is valid.")},
		{Tid_TRC_Error_TriggerRecordOfInterestSize2Big, _T("TriggerRecordOfInterest-size of {0} is too big. Maximal {1} is valid.")},
		{Tid_TRC_Error_ResetNotStart, _T("Reset of TriggerRecord-structure not started. Reset can not be finished.")},
		{Tid_TRC_Error_InvalidResetState, _T("Invalid Reset-state. Action can not be done.")},
		{Tid_TRC_Error_GetImageDefList, _T("Error in method GetImagDefList.")},
		{Tid_TRC_Error_GetDataDefList, _T("Error in method GetDataDefList.")},
		{Tid_TRC_Error_CopyValueObjData, _T("Error copying value object data")},
		{Tid_TRC_Error_GetTRCFailed, _T("Error getting TriggerRecordInstance. You must create it before call the get-function.")},
		{Tid_TRC_Error_CreateSMCommonData, _T("Error creating SharedMemory for Common data in TRC.")},
		{Tid_TRC_Error_InspectionSMData, _T("The SharedMemory for inspection data is invalid.")},
		{Tid_TRC_Error_TooManyImageBuffer, _T("Error too many image buffer for TRC requested. Max: {0}.")},
		{Tid_TRC_Error_InspectionPBTooLong, _T("Inspection protoBuf-message in TRC too long for shared memory.")},
		{Tid_TRC_Error_NotWriteVersion, _T("This TriggerRecord-version is readonly - not possible to get a RW-interface")},
		{Tid_TRC_Error_SMLoad, _T("Loading of the sharedMemory {0} failed.")},
		{Tid_TRC_Error_ImageProps, _T("Invalid image properties.")},
		{Tid_TRC_Error_EventCreation, _T("Creation of the TRC-Event failed, Error {0}")},
		{Tid_TRC_Error_GetValueWrongPos, _T("getDataValue failed, because the position {0} is invalid")},
		{Tid_TRC_Error_ValueNotReady, _T("getDataValue failed, because data not ready for reading")},
		{Tid_TRC_Error_NotEnoughFreeForLock, _T("Not enough triggerRecord free. Not possible to lock a triggerRecord.")},
		{Tid_TRC_Error_DecreaseFreeTRC, _T("Decrease of free triggerRecord failed. The number can not become lower than zero.")},
		{Tid_TRC_Error_GetInterestFailedLockFailed, _T("getTRofInterest failed because no lock obtained.")},
		{Tid_TRC_Error_setTrOfInterestNumberLockFailed, _T("setTrOfInterestNumber failed because no lock obtained.")},
		{Tid_TRC_Error_setTrOfInterestFailed, _T("setTrOfInterest failed.")},
		{Tid_TRC_Error_StopReloadingReader, _T("Stopping Reloading TRC-Reader, because of new reset.")},
		{Tid_TRC_Error_GetTRData, _T("GetTrData failed: Pos = {0}, TRNumber = {1}.")},

		{Tid_TRC_Error_ResetInspectionFailed, _T("Reset of TRC failed, because buffer creation failed.\nPossible Reason is too little resources, maybe the PPQs are too long.")},
		{Tid_TRC_Error_CounterTimeOut, _T("ResetCounter is not go back to zero in {0} seconds. Maybe a client is die without reset the counter. The current value is {1}.")},

		{Tid_NAK_Error_MissingEndFrame, _T("NAK! Acquisition End Frame missing for device {0} [Time {1} ms]")},

		{Tid_UpdateMainImages_InvalidImageBuffer, _T("Invalid Image Buffer.")},
		{Tid_UpdateMainImages_CameraNotFound, _T("Camera not found.")},
		{Tid_UpdateMainImages_InvalidCamera, _T("Invalid Camera.")},
		{Tid_UpdateMainImages_InvalidImage, _T("Invalid Image.")},

		{Tid_RunInspection_ResetTR, _T("TriggerRecord is old. Get new TriggerRecord.")},
		{Tid_RunInspection_TRFailed, _T("RunInspection failed, because TriggerRecord could not be created.")},
		{Tid_SetParameterToMonitorListFailed, _T("Not all parameter could be set.")},
		{Tid_SetAuxiliaryParameterToMonitorListFailed, _T("Not all auxiliary parameters could be set. Check if auxiliary is turned on correctly.") },
		{Tid_SetResultParameterToMonitorListFailed, _T("Not all result parameters could be set. Check if all needed results added to the analyzer: {0}")},

		{Tid_InvalidMemoryPointer, _T("Invalid Memory Pointer")},
		{Tid_InvalidMatroxType, _T("Invalid Matrox Type")},
		{Tid_InvalidMatroxAttribute, _T("Invalid Matrox Attribute")},

		{Tid_ErrorPpqTriggerCount, _T("The current configuration uses the variable 'PPQ_x.Trigger Count' in equations which is no longer allowed (respective tools will become invalid) as it is not synchronous to the inspection\nPlease replace all occurrences with the variable 'Tool Set.Trigger Count'")},
		{Tid_CircularReference, _T("A circular reference has been generated")},
		{Tid_EmptyObjectForIndirectValue, _T("Empty object for the indirect linked value")},
		{Tid_InvalidObjectForIndirectValue, _T("An invalid object is selected.")},
		{Tid_ErrorMemoryAllocation, _T("Memory allocation failed")},
		{Tid_ErrorMemoryBlockDataReservedSize, _T("Size of reserved memory block data to small")},
		{Tid_ErrorInRebuildTrcPosCache, _T("Exception in rebuild_trc_pos_cache")},
		{Tid_ErrorInGetProductData, _T("Exception in get_product_data")},

		{Tid_CreateThread, _T("ThreadID {0} created") },
		{Tid_DestroyThread, _T("ThreadID {0} destroyed")},
		{Tid_InvalidInputType, _T("The {0} ({1}) type is invalid.")},
		{Tid_InvalidInputValue, _T("The {0} ({1}) value is invalid.")},
		{Tid_InvalidInputObject, _T("The {0} ({1}) value is not {2}.")},
		{Tid_aTable, _T("a table")},
		{Tid_aTool, _T("a tool")},
		{Tid_anImage, _T("an image")},
		{Tid_aGrayImage, _T("a gray image")},
		{Tid_aColorImage, _T("a color image")},
		{Tid_aDecimalValue, _T("a decimal value")},
		{Tid_aTextValue, _T("a text value")},

		{Tid_ForbiddenNameForParameterName, _T("The name \"{0}\" is already used for another object in this parameter task.")},
		{Tid_DuplicateParameterName, _T("It is not allowed to have duplicated parameter names:\n {0}")},
		{Tid_DuplicateParameterNameWithLinked, _T("It is not allowed to have a parameter name which is already used\nby a linked parameter name: {0}")},
		{Tid_DuplicateParameterNameWithType, _T("It is not allowed to have a parameter name which is already used\nby a type parameter name: {0}.")},
		{Tid_SetParameterValuesFailed, _T("Setting of the parameter '{0}' failed.")},

		{Tid_Correct_Grouping_Add_S_Items, _T("Correct grouping add '{0}' Items.")},
		{Tid_GroupDependencies_Wrong, _T("Group Dependencies wrong. If the tool closed, it is not allowed to have dependencies outside of the Group Tool.")},

		{Tid_InvalidScaleFactor, _T("Invalid Scale Factor")},

		{Tid_LinearImageOperatorList_ResultCreateFailed, _T("Create of Results for LinearImageOperatorList failed.")},
		{Tid_LinearImageOperatorList_GetResultRangeFailed, _T("Get Range for the Result failed in LinearImageOperatorList.")},
		{Tid_BatchfileExecutionTimeout , _T("Execution of batchfile {0} timed out.")},
		{Tid_UnexpectedConversion , _T("Conversion in set value was not expected")},

		{Tid_CifxConfigReturnError , _T("Cifx configuration packet error return value 0x{0}")},
		{Tid_CifxInitializationSuccess , _T("Cifx initialization successful, ready to receive PLC data")},
		{Tid_CifxInitializationError , _T("Cifx initialization error")},
		{Tid_CifxClosed , _T("Cifx PLC connection closed")},
		{Tid_CifxPlcVersion , _T("Cifx send PLC data version {0}.{1}")},
		{Tid_CifxPlcConfigData , _T("Cifx send PLC config data: Layout {0}")},
		{Tid_CifxDllLoadError , _T("Cifx error, could not load CifX32DLL.dll")},
		{Tid_CifxVersionInfo , _T("Cifx Driver {0} {1} {2}")},
		{Tid_CifxResponseDataError , _T("Cifx error, writing response data")},
		{Tid_CifxPlcOpertaion , _T("Cifx, in operation mode")},

		{Tid_ModuleReady , _T("Module ready set to {0}")},
		{Tid_ModelTypeMismatch , _T("Model mismatch SVIM type is {0}, the loaded configuration is type {1}\nConfiguration shall not be able to go into Run mode")},
		{Tid_PlcOutputAlreadyUsed , _T("PLC Output {0} for {1} is already being used and cannot be imported with the value:\n{2}")},

		{Tid_Http_ConnectionError, _T("Client connection error: {0}")},
		{Tid_Http_ConnectionCloseError, _T("Error while closing http connection: {0}")},

		{Tid_WebSocket_ConnectionError, _T("WebSocket client connection error: {0}")},
		{Tid_WebSocket_ConnectionCloseError, _T("Error while closing websocket connection: {0}")},
		{Tid_WebSocket_PingTimeout, _T("Server did not respond to ping messages. Closing connection.")},

		{Tid_RPC_ReceivedTextMessage, _T("Received a text message, but only binary messages expected.")},
		{Tid_RPC_MessageTooLarge, _T("Message too large {0} bytes. Must not be larger than {1} bytes.")},
		{Tid_RPC_InvalidMessageType, _T("Invalid message type {0}")},

		{Tid_Gateway_SVObserverConnected , _T("Gateway successfully connected to SVObserver")},
		{Tid_Gateway_SVObserverDisconnected , _T("Connection to SVObserver lost")},
		{Tid_Gateway_TRC_NotAvailable , _T("TRC is not available. Unable to register callbacks!")},
		{Tid_Gateway_TRC_CreateTriggerRecordObjectFailed , _T("TRC returned invalid TRO for inspectionPos={0} and trId={1}")},
		{Tid_Gateway_TRC_PauseStateError , _T("TRC pause state polling error: {0}")},
		{Tid_Gateway_RequestPermissionsNotConfigured , _T("No permissions handling for message with payload type {0} configured!")},
		{Tid_Gateway_UserPermissionsNotConfigured , _T("Request of type {0} rejected because user {1} has no permissions configured.")},
		{Tid_Gateway_RequestNotAllowed , _T("Request of type {0} from user {1} rejected due to missing permissions.")},
		{Tid_Gateway_ReadValueFailed , _T("Error reading value with id {0}")},
		{Tid_Gateway_ReadImageFailed , _T("Error reading image with id {0} for inspection {1}")},

		{Tid_ShareControl_NoImageForId, _T("No Image for id found")},

		{Tid_SVRC_AccessDenied, _T("SVRC Access denied: Current state = {0}, Check state = {1}")},
		{Tid_InvalidValues, _T("Invalid input values")},
		{Tid_InvalidInputImage, _T("Invalid input image")},
		{Tid_InvalidOutputImage, _T("Invalid output image")},
		{Tid_InvalidParameterValue, _T("{0}: Invalid value. The value must between {1} and {2}.")},

		{Tid_ProductMissingNak, _T("NAK has been caused by a missing PPQ product")},
		{Tid_ImageMissingNak, _T("NAK has been caused by a missing camera image")},
		{Tid_InputMissingNak, _T("NAK has been caused by a missing input")},
		{Tid_ProductIncompleteNak, _T("NAK caused by product incomplete (usually PPQ full)")},
		{Tid_IsColorCheckForGrayscaleImage, _T("Color image checkbox selected, but image is grayscale")},
		{Tid_WrongParentForEmbeddedValue, _T("wrong Parent for Embedded Value ")},
		{Tid_FileNameInvalid, _T("File name is invalid {0}")},
		{Tid_WrongParentForEmbeddedValue, _T("Wrong Parent for Embedded Value ")},
		{Tid_ErrorWrite, _T("Error writing Archive data '{0}'!")},
		{Tid_ErrorArchiveQueueFull, _T("Error writing Archive Queue is full!")},

		{Tid_Value_MustThan, _T("{0} must be {1} than {2}.")},
		{Tid_Greater, _T("greater")},
		{Tid_ValidateValue_MinMaxInvalid, _T("Validate Value failed: Not between min and max")},
		{Tid_ObjectNotFound, _T("Object with the id {0} not found.")},
		{Tid_NameContainsInvalidChars, _T("Name contains invalid special characters.")},
		{Tid_ProductNotTriggered, _T("SVPPQObject::StartInspection product not triggerd")},
		{Tid_ErrorStartInspection, _T("Insepection coul not be started")},
		{Tid_MaxDepthOfToolsError, _T("Too many tools nested.")},
		{Tid_NoParentExtentForAnalyzer, _T("For Analyzer is not a parent extent possible.")},
		{Tid_SetOfReadOnlyValueFailed, _T("Value is readOnly. Set is forbidden.")},
		{Tid_SetOfValueFailed, _T("Set of embeddedValue with the ID {0} failed.")},
		{Tid_DuplicateObjectId, _T("By creating an object, there is a duplicate of the objectId %s found.")},
		{Tid_RejectClarifyFailedNoTR, _T("Reject clarification failed, no valid triggerRecord.")},
		{Tid_RejectClarifyFailedUnknowData, _T("Reject clarification failed, unknown data: {}.")},
		{Tid_ModuleNameAlreadyUsed, _T("The Modulename \"{0}\" already used.")},
};
} //namespace SvStl