#pragma once
enum  svModeEnum
{
	SVIM_MODE_UNKNOWN = 0,
	SVIM_MODE_ONLINE,
	SVIM_MODE_OFFLINE,
	SVIM_MODE_REGRESSION,
	SVIM_MODE_TEST,
	SVIM_MODE_EDIT,
	SVIM_MODE_CHANGING = 100,
	SVIM_MODE_REMOVE = 0x8000,
};

